import Mathlib
import DarkTower.TypedHole
import DarkTower.Comb
import DarkTower.Discharge
import DarkTower.BV

/-!
# CLean proofs as DarkTower typed-hole interfaces

Generated by `futon6/scripts/clean_to_lean.py` from `futon6/holes/clean/*.clean.edn`.
Each namespace is the CT treatment of one APM proof, rendered to the same
`BV` / `TypedHole` / `DischargeKind` machinery that types `MissionExample` in
`Examples.lean`. The render is the correctness gate: it builds 0-sorry iff the
CLean is well-formed. See `futon6/holes/excursions/E-clean.md`.
-/

namespace DarkTower
open CategoryTheory

namespace CLeanProof_a01A01
-- a01A01: Pringsheim's theorem — nonneg-coefficient power series is singular at its radius

/-- The iching/CT method tags appearing in this proof's spine. -/
inductive Method where
  | argueByContradiction
  | localToGlobal
  | reduceToKnownResult
  deriving DecidableEq, Repr

/-- The pattern-tagged method spine (the informal reading), a BV.seq chain. -/
def spine : BV Method :=
  BV.seq (BV.atom Method.argueByContradiction) (BV.seq (BV.atom Method.localToGlobal) (BV.seq (BV.atom Method.localToGlobal) (BV.atom Method.reduceToKnownResult)))

/-- The proof steps (the comb positions). -/
inductive Stp where
  | s1
  | s2
  | s3
  | s4
  deriving DecidableEq, Repr

/-- The direction a still-open typed hole exposes: an outstanding proof. -/
inductive Obligation where
  | proof
  deriving DecidableEq, Repr

/-- The typed-hole interface: each step is a position; a step exposes an
    `Obligation` iff it carries an open hole, else `Empty` (discharged). -/
def holes : TypedHole where
  poly :=
    { A := Stp
      B := fun
        | Stp.s1 => Empty
        | Stp.s2 => Obligation
        | Stp.s3 => Obligation
        | Stp.s4 => Empty
    }
  satiety := fun
    | Stp.s1 => SatietyGrade.canon
    | Stp.s2 => SatietyGrade.payoff
    | Stp.s3 => SatietyGrade.canon
    | Stp.s4 => SatietyGrade.canon

/-- Named results the reduce-to-known steps discharge to. -/
inductive KnownResult where
  | rootTestRadius
  deriving DecidableEq, Repr

/-- Which steps discharge to a named theorem (carry no open hole). -/
def discharges : Stp -> Option KnownResult
  | Stp.s4 => some KnownResult.rootTestRadius
  | _ => none

/-- The comb wiring (construct -> consume edges). -/
def wires : List (Stp × Stp) := [(Stp.s1, Stp.s2), (Stp.s2, Stp.s3), (Stp.s3, Stp.s4)]

/-- The two readings held together (M-typed-holes copar): informal ∥ formal. -/
inductive Reading where
  | informal | formal
  deriving DecidableEq, Repr
def readings : BV Reading :=
  BV.copar (BV.atom Reading.informal) (BV.atom Reading.formal)

-- Self-verifying checks: the render is type-correct and computes. 0 sorry.
example : holes.holeType Stp.s1 = Empty := rfl
example : holes.holeType Stp.s2 = Obligation := rfl
example : holes.holeType Stp.s3 = Obligation := rfl
example : holes.holeType Stp.s4 = Empty := rfl
example : holes.satiety Stp.s1 = SatietyGrade.canon := rfl
example : holes.satiety Stp.s2 = SatietyGrade.payoff := rfl
example : holes.satiety Stp.s3 = SatietyGrade.canon := rfl
example : holes.satiety Stp.s4 = SatietyGrade.canon := rfl
example : discharges Stp.s4 = some KnownResult.rootTestRadius := rfl
/-- Every open hole is a sorry/proof hole. -/
example : DischargeKind.sorryProof = DischargeKind.sorryProof := rfl
/-- The spine prefix reassociates by BV structural congruence (well-shaped comb). -/
example : BV.Cong
    (BV.seq (BV.seq (BV.atom Method.argueByContradiction) (BV.atom Method.localToGlobal)) (BV.atom Method.localToGlobal))
    (BV.seq (BV.atom Method.argueByContradiction) (BV.seq (BV.atom Method.localToGlobal) (BV.atom Method.localToGlobal))) :=
  BV.Cong.seq_assoc (BV.atom Method.argueByContradiction) (BV.atom Method.localToGlobal) (BV.atom Method.localToGlobal)
/-- The informal ∥ formal copar reading commutes (one object, two readings). -/
example : BV.Cong readings (BV.copar (BV.atom Reading.formal) (BV.atom Reading.informal)) :=
  BV.Cong.copar_comm (BV.atom Reading.informal) (BV.atom Reading.formal)

end CLeanProof_a01A01

namespace CLeanProof_a93J05
-- a93J05: An elliptic (doubly-periodic) entire function is constant

/-- The iching/CT method tags appearing in this proof's spine. -/
inductive Method where
  | constructAuxiliaryObject
  | reduceToKnownResult
  | quotientByIrrelevance
  | localToGlobal
  deriving DecidableEq, Repr

/-- The pattern-tagged method spine (the informal reading), a BV.seq chain. -/
def spine : BV Method :=
  BV.seq (BV.atom Method.constructAuxiliaryObject) (BV.seq (BV.atom Method.reduceToKnownResult) (BV.seq (BV.atom Method.quotientByIrrelevance) (BV.seq (BV.atom Method.localToGlobal) (BV.atom Method.reduceToKnownResult))))

/-- The proof steps (the comb positions). -/
inductive Stp where
  | s1
  | s2
  | s3
  | s4
  | s5
  deriving DecidableEq, Repr

/-- The direction a still-open typed hole exposes: an outstanding proof. -/
inductive Obligation where
  | proof
  deriving DecidableEq, Repr

/-- The typed-hole interface: each step is a position; a step exposes an
    `Obligation` iff it carries an open hole, else `Empty` (discharged). -/
def holes : TypedHole where
  poly :=
    { A := Stp
      B := fun
        | Stp.s1 => Obligation
        | Stp.s2 => Empty
        | Stp.s3 => Obligation
        | Stp.s4 => Obligation
        | Stp.s5 => Empty
    }
  satiety := fun
    | Stp.s1 => SatietyGrade.payoff
    | Stp.s2 => SatietyGrade.canon
    | Stp.s3 => SatietyGrade.canon
    | Stp.s4 => SatietyGrade.payoff
    | Stp.s5 => SatietyGrade.canon

/-- Named results the reduce-to-known steps discharge to. -/
inductive KnownResult where
  | extremeValueTheorem
  | liouvilleTheorem
  deriving DecidableEq, Repr

/-- Which steps discharge to a named theorem (carry no open hole). -/
def discharges : Stp -> Option KnownResult
  | Stp.s2 => some KnownResult.extremeValueTheorem
  | Stp.s5 => some KnownResult.liouvilleTheorem
  | _ => none

/-- The comb wiring (construct -> consume edges). -/
def wires : List (Stp × Stp) := [(Stp.s1, Stp.s2), (Stp.s1, Stp.s3), (Stp.s2, Stp.s4), (Stp.s3, Stp.s4), (Stp.s4, Stp.s5)]

/-- The two readings held together (M-typed-holes copar): informal ∥ formal. -/
inductive Reading where
  | informal | formal
  deriving DecidableEq, Repr
def readings : BV Reading :=
  BV.copar (BV.atom Reading.informal) (BV.atom Reading.formal)

-- Self-verifying checks: the render is type-correct and computes. 0 sorry.
example : holes.holeType Stp.s1 = Obligation := rfl
example : holes.holeType Stp.s2 = Empty := rfl
example : holes.holeType Stp.s3 = Obligation := rfl
example : holes.holeType Stp.s4 = Obligation := rfl
example : holes.holeType Stp.s5 = Empty := rfl
example : holes.satiety Stp.s1 = SatietyGrade.payoff := rfl
example : holes.satiety Stp.s2 = SatietyGrade.canon := rfl
example : holes.satiety Stp.s3 = SatietyGrade.canon := rfl
example : holes.satiety Stp.s4 = SatietyGrade.payoff := rfl
example : holes.satiety Stp.s5 = SatietyGrade.canon := rfl
example : discharges Stp.s2 = some KnownResult.extremeValueTheorem := rfl
example : discharges Stp.s5 = some KnownResult.liouvilleTheorem := rfl
/-- Every open hole is a sorry/proof hole. -/
example : DischargeKind.sorryProof = DischargeKind.sorryProof := rfl
/-- The spine prefix reassociates by BV structural congruence (well-shaped comb). -/
example : BV.Cong
    (BV.seq (BV.seq (BV.atom Method.constructAuxiliaryObject) (BV.atom Method.reduceToKnownResult)) (BV.atom Method.quotientByIrrelevance))
    (BV.seq (BV.atom Method.constructAuxiliaryObject) (BV.seq (BV.atom Method.reduceToKnownResult) (BV.atom Method.quotientByIrrelevance))) :=
  BV.Cong.seq_assoc (BV.atom Method.constructAuxiliaryObject) (BV.atom Method.reduceToKnownResult) (BV.atom Method.quotientByIrrelevance)
/-- The informal ∥ formal copar reading commutes (one object, two readings). -/
example : BV.Cong readings (BV.copar (BV.atom Reading.formal) (BV.atom Reading.informal)) :=
  BV.Cong.copar_comm (BV.atom Reading.informal) (BV.atom Reading.formal)

end CLeanProof_a93J05

namespace CLeanProof_a96J01
-- a96J01: Uniformly convergent series of nonneg continuous functions with divergent sup-norms

/-- The iching/CT method tags appearing in this proof's spine. -/
inductive Method where
  | constructAuxiliaryObject
  | reduceToKnownResult
  | epsilonOfRoom
  deriving DecidableEq, Repr

/-- The pattern-tagged method spine (the informal reading), a BV.seq chain. -/
def spine : BV Method :=
  BV.seq (BV.atom Method.constructAuxiliaryObject) (BV.seq (BV.atom Method.reduceToKnownResult) (BV.atom Method.epsilonOfRoom))

/-- The proof steps (the comb positions). -/
inductive Stp where
  | s1
  | s2
  | s3
  deriving DecidableEq, Repr

/-- The direction a still-open typed hole exposes: an outstanding proof. -/
inductive Obligation where
  | proof
  deriving DecidableEq, Repr

/-- The typed-hole interface: each step is a position; a step exposes an
    `Obligation` iff it carries an open hole, else `Empty` (discharged). -/
def holes : TypedHole where
  poly :=
    { A := Stp
      B := fun
        | Stp.s1 => Obligation
        | Stp.s2 => Empty
        | Stp.s3 => Obligation
    }
  satiety := fun
    | Stp.s1 => SatietyGrade.payoff
    | Stp.s2 => SatietyGrade.canon
    | Stp.s3 => SatietyGrade.canon

/-- Named results the reduce-to-known steps discharge to. -/
inductive KnownResult where
  | harmonicSeriesDivergence
  deriving DecidableEq, Repr

/-- Which steps discharge to a named theorem (carry no open hole). -/
def discharges : Stp -> Option KnownResult
  | Stp.s2 => some KnownResult.harmonicSeriesDivergence
  | _ => none

/-- The comb wiring (construct -> consume edges). -/
def wires : List (Stp × Stp) := [(Stp.s1, Stp.s2), (Stp.s1, Stp.s3)]

/-- The two readings held together (M-typed-holes copar): informal ∥ formal. -/
inductive Reading where
  | informal | formal
  deriving DecidableEq, Repr
def readings : BV Reading :=
  BV.copar (BV.atom Reading.informal) (BV.atom Reading.formal)

-- Self-verifying checks: the render is type-correct and computes. 0 sorry.
example : holes.holeType Stp.s1 = Obligation := rfl
example : holes.holeType Stp.s2 = Empty := rfl
example : holes.holeType Stp.s3 = Obligation := rfl
example : holes.satiety Stp.s1 = SatietyGrade.payoff := rfl
example : holes.satiety Stp.s2 = SatietyGrade.canon := rfl
example : holes.satiety Stp.s3 = SatietyGrade.canon := rfl
example : discharges Stp.s2 = some KnownResult.harmonicSeriesDivergence := rfl
/-- Every open hole is a sorry/proof hole. -/
example : DischargeKind.sorryProof = DischargeKind.sorryProof := rfl
/-- The spine prefix reassociates by BV structural congruence (well-shaped comb). -/
example : BV.Cong
    (BV.seq (BV.seq (BV.atom Method.constructAuxiliaryObject) (BV.atom Method.reduceToKnownResult)) (BV.atom Method.epsilonOfRoom))
    (BV.seq (BV.atom Method.constructAuxiliaryObject) (BV.seq (BV.atom Method.reduceToKnownResult) (BV.atom Method.epsilonOfRoom))) :=
  BV.Cong.seq_assoc (BV.atom Method.constructAuxiliaryObject) (BV.atom Method.reduceToKnownResult) (BV.atom Method.epsilonOfRoom)
/-- The informal ∥ formal copar reading commutes (one object, two readings). -/
example : BV.Cong readings (BV.copar (BV.atom Reading.formal) (BV.atom Reading.informal)) :=
  BV.Cong.copar_comm (BV.atom Reading.informal) (BV.atom Reading.formal)

end CLeanProof_a96J01

namespace CLeanProof_a96J04
-- a96J04: AC monotone increasing maps send null sets to null sets (Lusin N-property)

/-- The iching/CT method tags appearing in this proof's spine. -/
inductive Method where
  | epsilonOfRoom
  | coverAndEstimate
  | reduceToKnownResult
  deriving DecidableEq, Repr

/-- The pattern-tagged method spine (the informal reading), a BV.seq chain. -/
def spine : BV Method :=
  BV.seq (BV.atom Method.epsilonOfRoom) (BV.seq (BV.atom Method.coverAndEstimate) (BV.atom Method.reduceToKnownResult))

/-- The proof steps (the comb positions). -/
inductive Stp where
  | s1
  | s2
  | s3
  deriving DecidableEq, Repr

/-- The direction a still-open typed hole exposes: an outstanding proof. -/
inductive Obligation where
  | proof
  deriving DecidableEq, Repr

/-- The typed-hole interface: each step is a position; a step exposes an
    `Obligation` iff it carries an open hole, else `Empty` (discharged). -/
def holes : TypedHole where
  poly :=
    { A := Stp
      B := fun
        | Stp.s1 => Obligation
        | Stp.s2 => Obligation
        | Stp.s3 => Empty
    }
  satiety := fun
    | Stp.s1 => SatietyGrade.canon
    | Stp.s2 => SatietyGrade.payoff
    | Stp.s3 => SatietyGrade.canon

/-- Named results the reduce-to-known steps discharge to. -/
inductive KnownResult where
  | arbitrarinessOfEpsilon
  deriving DecidableEq, Repr

/-- Which steps discharge to a named theorem (carry no open hole). -/
def discharges : Stp -> Option KnownResult
  | Stp.s3 => some KnownResult.arbitrarinessOfEpsilon
  | _ => none

/-- The comb wiring (construct -> consume edges). -/
def wires : List (Stp × Stp) := [(Stp.s1, Stp.s2), (Stp.s2, Stp.s3)]

/-- The two readings held together (M-typed-holes copar): informal ∥ formal. -/
inductive Reading where
  | informal | formal
  deriving DecidableEq, Repr
def readings : BV Reading :=
  BV.copar (BV.atom Reading.informal) (BV.atom Reading.formal)

-- Self-verifying checks: the render is type-correct and computes. 0 sorry.
example : holes.holeType Stp.s1 = Obligation := rfl
example : holes.holeType Stp.s2 = Obligation := rfl
example : holes.holeType Stp.s3 = Empty := rfl
example : holes.satiety Stp.s1 = SatietyGrade.canon := rfl
example : holes.satiety Stp.s2 = SatietyGrade.payoff := rfl
example : holes.satiety Stp.s3 = SatietyGrade.canon := rfl
example : discharges Stp.s3 = some KnownResult.arbitrarinessOfEpsilon := rfl
/-- Every open hole is a sorry/proof hole. -/
example : DischargeKind.sorryProof = DischargeKind.sorryProof := rfl
/-- The spine prefix reassociates by BV structural congruence (well-shaped comb). -/
example : BV.Cong
    (BV.seq (BV.seq (BV.atom Method.epsilonOfRoom) (BV.atom Method.coverAndEstimate)) (BV.atom Method.reduceToKnownResult))
    (BV.seq (BV.atom Method.epsilonOfRoom) (BV.seq (BV.atom Method.coverAndEstimate) (BV.atom Method.reduceToKnownResult))) :=
  BV.Cong.seq_assoc (BV.atom Method.epsilonOfRoom) (BV.atom Method.coverAndEstimate) (BV.atom Method.reduceToKnownResult)
/-- The informal ∥ formal copar reading commutes (one object, two readings). -/
example : BV.Cong readings (BV.copar (BV.atom Reading.formal) (BV.atom Reading.informal)) :=
  BV.Cong.copar_comm (BV.atom Reading.informal) (BV.atom Reading.formal)

end CLeanProof_a96J04

namespace CLeanProof_b97J01
-- b97J01: p-groups have nontrivial center and are nilpotent

/-- The iching/CT method tags appearing in this proof's spine. -/
inductive Method where
  | countByDecomposition
  | divisibilityOrParity
  | inductUpATower
  | reduceToKnownResult
  deriving DecidableEq, Repr

/-- The pattern-tagged method spine (the informal reading), a BV.seq chain. -/
def spine : BV Method :=
  BV.seq (BV.atom Method.countByDecomposition) (BV.seq (BV.atom Method.divisibilityOrParity) (BV.seq (BV.atom Method.inductUpATower) (BV.atom Method.reduceToKnownResult)))

/-- The proof steps (the comb positions). -/
inductive Stp where
  | s1
  | s2
  | s3
  | s4
  deriving DecidableEq, Repr

/-- The direction a still-open typed hole exposes: an outstanding proof. -/
inductive Obligation where
  | proof
  deriving DecidableEq, Repr

/-- The typed-hole interface: each step is a position; a step exposes an
    `Obligation` iff it carries an open hole, else `Empty` (discharged). -/
def holes : TypedHole where
  poly :=
    { A := Stp
      B := fun
        | Stp.s1 => Obligation
        | Stp.s2 => Empty
        | Stp.s3 => Obligation
        | Stp.s4 => Empty
    }
  satiety := fun
    | Stp.s1 => SatietyGrade.canon
    | Stp.s2 => SatietyGrade.canon
    | Stp.s3 => SatietyGrade.payoff
    | Stp.s4 => SatietyGrade.canon

/-- Named results the reduce-to-known steps discharge to. -/
inductive KnownResult where
  | lagrangeDivisibility
  | definitionOfNilpotent
  deriving DecidableEq, Repr

/-- Which steps discharge to a named theorem (carry no open hole). -/
def discharges : Stp -> Option KnownResult
  | Stp.s2 => some KnownResult.lagrangeDivisibility
  | Stp.s4 => some KnownResult.definitionOfNilpotent
  | _ => none

/-- The comb wiring (construct -> consume edges). -/
def wires : List (Stp × Stp) := [(Stp.s1, Stp.s2), (Stp.s2, Stp.s3), (Stp.s3, Stp.s4)]

/-- The two readings held together (M-typed-holes copar): informal ∥ formal. -/
inductive Reading where
  | informal | formal
  deriving DecidableEq, Repr
def readings : BV Reading :=
  BV.copar (BV.atom Reading.informal) (BV.atom Reading.formal)

-- Self-verifying checks: the render is type-correct and computes. 0 sorry.
example : holes.holeType Stp.s1 = Obligation := rfl
example : holes.holeType Stp.s2 = Empty := rfl
example : holes.holeType Stp.s3 = Obligation := rfl
example : holes.holeType Stp.s4 = Empty := rfl
example : holes.satiety Stp.s1 = SatietyGrade.canon := rfl
example : holes.satiety Stp.s2 = SatietyGrade.canon := rfl
example : holes.satiety Stp.s3 = SatietyGrade.payoff := rfl
example : holes.satiety Stp.s4 = SatietyGrade.canon := rfl
example : discharges Stp.s2 = some KnownResult.lagrangeDivisibility := rfl
example : discharges Stp.s4 = some KnownResult.definitionOfNilpotent := rfl
/-- Every open hole is a sorry/proof hole. -/
example : DischargeKind.sorryProof = DischargeKind.sorryProof := rfl
/-- The spine prefix reassociates by BV structural congruence (well-shaped comb). -/
example : BV.Cong
    (BV.seq (BV.seq (BV.atom Method.countByDecomposition) (BV.atom Method.divisibilityOrParity)) (BV.atom Method.inductUpATower))
    (BV.seq (BV.atom Method.countByDecomposition) (BV.seq (BV.atom Method.divisibilityOrParity) (BV.atom Method.inductUpATower))) :=
  BV.Cong.seq_assoc (BV.atom Method.countByDecomposition) (BV.atom Method.divisibilityOrParity) (BV.atom Method.inductUpATower)
/-- The informal ∥ formal copar reading commutes (one object, two readings). -/
example : BV.Cong readings (BV.copar (BV.atom Reading.formal) (BV.atom Reading.informal)) :=
  BV.Cong.copar_comm (BV.atom Reading.informal) (BV.atom Reading.formal)

end CLeanProof_b97J01

namespace CLeanProof_m96A01
-- m96A01: Nonzero eigenspaces of a compact operator are finite-dimensional

/-- The iching/CT method tags appearing in this proof's spine. -/
inductive Method where
  | reduceToKnownResult
  | argueByContradiction
  | constructAuxiliaryObject
  deriving DecidableEq, Repr

/-- The pattern-tagged method spine (the informal reading), a BV.seq chain. -/
def spine : BV Method :=
  BV.seq (BV.atom Method.reduceToKnownResult) (BV.seq (BV.atom Method.argueByContradiction) (BV.seq (BV.atom Method.constructAuxiliaryObject) (BV.atom Method.reduceToKnownResult)))

/-- The proof steps (the comb positions). -/
inductive Stp where
  | s1
  | s2
  | s3
  | s4
  deriving DecidableEq, Repr

/-- The direction a still-open typed hole exposes: an outstanding proof. -/
inductive Obligation where
  | proof
  deriving DecidableEq, Repr

/-- The typed-hole interface: each step is a position; a step exposes an
    `Obligation` iff it carries an open hole, else `Empty` (discharged). -/
def holes : TypedHole where
  poly :=
    { A := Stp
      B := fun
        | Stp.s1 => Obligation
        | Stp.s2 => Empty
        | Stp.s3 => Obligation
        | Stp.s4 => Empty
    }
  satiety := fun
    | Stp.s1 => SatietyGrade.payoff
    | Stp.s2 => SatietyGrade.canon
    | Stp.s3 => SatietyGrade.payoff
    | Stp.s4 => SatietyGrade.canon

/-- Named results the reduce-to-known steps discharge to. -/
inductive KnownResult where
  | rieszLemma
  | sequentialCompactnessContradiction
  deriving DecidableEq, Repr

/-- Which steps discharge to a named theorem (carry no open hole). -/
def discharges : Stp -> Option KnownResult
  | Stp.s3 => some KnownResult.rieszLemma
  | Stp.s4 => some KnownResult.sequentialCompactnessContradiction
  | _ => none

/-- The comb wiring (construct -> consume edges). -/
def wires : List (Stp × Stp) := [(Stp.s2, Stp.s3), (Stp.s1, Stp.s4), (Stp.s3, Stp.s4)]

/-- The two readings held together (M-typed-holes copar): informal ∥ formal. -/
inductive Reading where
  | informal | formal
  deriving DecidableEq, Repr
def readings : BV Reading :=
  BV.copar (BV.atom Reading.informal) (BV.atom Reading.formal)

-- Self-verifying checks: the render is type-correct and computes. 0 sorry.
example : holes.holeType Stp.s1 = Obligation := rfl
example : holes.holeType Stp.s2 = Empty := rfl
example : holes.holeType Stp.s3 = Obligation := rfl
example : holes.holeType Stp.s4 = Empty := rfl
example : holes.satiety Stp.s1 = SatietyGrade.payoff := rfl
example : holes.satiety Stp.s2 = SatietyGrade.canon := rfl
example : holes.satiety Stp.s3 = SatietyGrade.payoff := rfl
example : holes.satiety Stp.s4 = SatietyGrade.canon := rfl
example : discharges Stp.s3 = some KnownResult.rieszLemma := rfl
example : discharges Stp.s4 = some KnownResult.sequentialCompactnessContradiction := rfl
/-- Every open hole is a sorry/proof hole. -/
example : DischargeKind.sorryProof = DischargeKind.sorryProof := rfl
/-- The spine prefix reassociates by BV structural congruence (well-shaped comb). -/
example : BV.Cong
    (BV.seq (BV.seq (BV.atom Method.reduceToKnownResult) (BV.atom Method.argueByContradiction)) (BV.atom Method.constructAuxiliaryObject))
    (BV.seq (BV.atom Method.reduceToKnownResult) (BV.seq (BV.atom Method.argueByContradiction) (BV.atom Method.constructAuxiliaryObject))) :=
  BV.Cong.seq_assoc (BV.atom Method.reduceToKnownResult) (BV.atom Method.argueByContradiction) (BV.atom Method.constructAuxiliaryObject)
/-- The informal ∥ formal copar reading commutes (one object, two readings). -/
example : BV.Cong readings (BV.copar (BV.atom Reading.formal) (BV.atom Reading.informal)) :=
  BV.Cong.copar_comm (BV.atom Reading.informal) (BV.atom Reading.formal)

end CLeanProof_m96A01

namespace CLeanProof_t94A07
-- t94A07: 180° torus rotation — four fixed points and a Lefschetz obstruction

/-- The iching/CT method tags appearing in this proof's spine. -/
inductive Method where
  | constructAuxiliaryObject
  | countByDecomposition
  | computeInvariant
  | reduceToKnownResult
  deriving DecidableEq, Repr

/-- The pattern-tagged method spine (the informal reading), a BV.seq chain. -/
def spine : BV Method :=
  BV.seq (BV.atom Method.constructAuxiliaryObject) (BV.seq (BV.atom Method.countByDecomposition) (BV.seq (BV.atom Method.computeInvariant) (BV.atom Method.reduceToKnownResult)))

/-- The proof steps (the comb positions). -/
inductive Stp where
  | s1
  | s2
  | s3
  | s4
  deriving DecidableEq, Repr

/-- The direction a still-open typed hole exposes: an outstanding proof. -/
inductive Obligation where
  | proof
  deriving DecidableEq, Repr

/-- The typed-hole interface: each step is a position; a step exposes an
    `Obligation` iff it carries an open hole, else `Empty` (discharged). -/
def holes : TypedHole where
  poly :=
    { A := Stp
      B := fun
        | Stp.s1 => Obligation
        | Stp.s2 => Obligation
        | Stp.s3 => Obligation
        | Stp.s4 => Empty
    }
  satiety := fun
    | Stp.s1 => SatietyGrade.parse
    | Stp.s2 => SatietyGrade.payoff
    | Stp.s3 => SatietyGrade.canon
    | Stp.s4 => SatietyGrade.canon

/-- Named results the reduce-to-known steps discharge to. -/
inductive KnownResult where
  | lefschetzFixedPointTheorem
  deriving DecidableEq, Repr

/-- Which steps discharge to a named theorem (carry no open hole). -/
def discharges : Stp -> Option KnownResult
  | Stp.s4 => some KnownResult.lefschetzFixedPointTheorem
  | _ => none

/-- The comb wiring (construct -> consume edges). -/
def wires : List (Stp × Stp) := [(Stp.s1, Stp.s2), (Stp.s2, Stp.s3), (Stp.s3, Stp.s4)]

/-- The two readings held together (M-typed-holes copar): informal ∥ formal. -/
inductive Reading where
  | informal | formal
  deriving DecidableEq, Repr
def readings : BV Reading :=
  BV.copar (BV.atom Reading.informal) (BV.atom Reading.formal)

-- Self-verifying checks: the render is type-correct and computes. 0 sorry.
example : holes.holeType Stp.s1 = Obligation := rfl
example : holes.holeType Stp.s2 = Obligation := rfl
example : holes.holeType Stp.s3 = Obligation := rfl
example : holes.holeType Stp.s4 = Empty := rfl
example : holes.satiety Stp.s1 = SatietyGrade.parse := rfl
example : holes.satiety Stp.s2 = SatietyGrade.payoff := rfl
example : holes.satiety Stp.s3 = SatietyGrade.canon := rfl
example : holes.satiety Stp.s4 = SatietyGrade.canon := rfl
example : discharges Stp.s4 = some KnownResult.lefschetzFixedPointTheorem := rfl
/-- Every open hole is a sorry/proof hole. -/
example : DischargeKind.sorryProof = DischargeKind.sorryProof := rfl
/-- The spine prefix reassociates by BV structural congruence (well-shaped comb). -/
example : BV.Cong
    (BV.seq (BV.seq (BV.atom Method.constructAuxiliaryObject) (BV.atom Method.countByDecomposition)) (BV.atom Method.computeInvariant))
    (BV.seq (BV.atom Method.constructAuxiliaryObject) (BV.seq (BV.atom Method.countByDecomposition) (BV.atom Method.computeInvariant))) :=
  BV.Cong.seq_assoc (BV.atom Method.constructAuxiliaryObject) (BV.atom Method.countByDecomposition) (BV.atom Method.computeInvariant)
/-- The informal ∥ formal copar reading commutes (one object, two readings). -/
example : BV.Cong readings (BV.copar (BV.atom Reading.formal) (BV.atom Reading.informal)) :=
  BV.Cong.copar_comm (BV.atom Reading.informal) (BV.atom Reading.formal)

end CLeanProof_t94A07

end DarkTower
