import Mathlib
import DarkTower.TypedHole
import DarkTower.Comb
import DarkTower.Discharge
import DarkTower.BV
import DarkTower.ExperimentPreregistration
import DarkTower.ExperimentalDesign

/-!
# CLean experiments as prospective DarkTower registrations

Generated by `futon6/scripts/clean_to_lean.py` from an experiment-shaped CLean
EDN. The EDN is the authority: axes, arms, complete seed triples, stop rules,
and the total decision function below are all rendered from it.
-/

namespace DarkTower
open CategoryTheory

namespace CLeanProof_nonseedable_pilot_fixture
-- nonseedable-pilot-fixture: Measured-variation pilot over problem identifiers

/-- The iching/CT method tags appearing in this proof's spine. -/
inductive Method where
  | register
  | run
  | classify
  deriving DecidableEq, Repr

/-- The pattern-tagged method spine (the informal reading), a BV.seq chain. -/
def spine : BV Method :=
  BV.seq (BV.atom Method.register) (BV.seq (BV.atom Method.run) (BV.atom Method.classify))

/-- The proof steps (the comb positions). -/
inductive Stp where
  | e1
  | e2
  | e3
  deriving DecidableEq, Repr

/-- The direction a still-open typed hole exposes: an outstanding proof. -/
inductive Obligation where
  | proof
  deriving DecidableEq, Repr

/-- The typed-hole interface: each step is a position; a step exposes an
    `Obligation` iff it carries an open hole, else `Empty` (discharged). -/
def holes : TypedHole where
  poly :=
    { A := Stp
      B := fun
        | Stp.e1 => Empty
        | Stp.e2 => Empty
        | Stp.e3 => Empty
    }
  satiety := fun
    | Stp.e1 => SatietyGrade.canon
    | Stp.e2 => SatietyGrade.canon
    | Stp.e3 => SatietyGrade.canon

/-- The comb wiring (construct -> consume edges). -/
def wires : List (Stp × Stp) := [(Stp.e1, Stp.e2), (Stp.e2, Stp.e3)]

/-- The readings held together (M-typed-holes copar): informal ∥ formal ∥ executable. -/
inductive Reading where
  | informal
  | formal
  | executable
  deriving DecidableEq, Repr
def readings : BV Reading :=
  BV.copar (BV.atom Reading.informal) (BV.copar (BV.atom Reading.formal) (BV.atom Reading.executable))

-- Self-verifying checks: the experiment pipeline is type-correct and computes.
example : holes.holeType Stp.e1 = Empty := rfl
example : holes.holeType Stp.e2 = Empty := rfl
example : holes.holeType Stp.e3 = Empty := rfl
example : holes.satiety Stp.e1 = SatietyGrade.canon := rfl
example : holes.satiety Stp.e2 = SatietyGrade.canon := rfl
example : holes.satiety Stp.e3 = SatietyGrade.canon := rfl
/-- The spine prefix reassociates by BV structural congruence (well-shaped comb). -/
example : BV.Cong
    (BV.seq (BV.seq (BV.atom Method.register) (BV.atom Method.run)) (BV.atom Method.classify))
    (BV.seq (BV.atom Method.register) (BV.seq (BV.atom Method.run) (BV.atom Method.classify))) :=
  BV.Cong.seq_assoc (BV.atom Method.register) (BV.atom Method.run) (BV.atom Method.classify)
/-- The informal ∥ formal copar reading commutes (one object, its readings). -/
example : BV.Cong (BV.copar (BV.atom Reading.informal) (BV.atom Reading.formal)) (BV.copar (BV.atom Reading.formal) (BV.atom Reading.informal)) :=
  BV.Cong.copar_comm (BV.atom Reading.informal) (BV.atom Reading.formal)

end CLeanProof_nonseedable_pilot_fixture

namespace CLeanExperiment_nonseedable_pilot_fixture
-- nonseedable-pilot-fixture: Measured-variation pilot over problem identifiers

open ExperimentPreregistration
open ExperimentalDesign

inductive Scenario where
  | problemAlpha
  deriving DecidableEq, Repr

/-- withholding the registered memory changes the offered set -/
noncomputable def memoryAxis : Axis where
  name := "memory"
  levels := [0, 1]
  score := fun x => x

theorem memoryAxis_navigable : memoryAxis.Navigable := by
  norm_num [Axis.Navigable, Axis.gradientSteps, memoryAxis]

noncomputable def controlArm : Arm where
  name := "control"
  neutral := true
  axes := []
  role := ArmRole.baselineNeutral

noncomputable def withoutMemoryArm : Arm where
  name := "without-memory"
  neutral := false
  axes := [memoryAxis]
  role := ArmRole.treatment

inductive TraceClass where
  | complete
  | invalid
  deriving DecidableEq, Repr

inductive Outcome where
  | accept
  | reject
  deriving DecidableEq, Repr

structure ExperimentTrace where
  classification : TraceClass
  boundaryRefused : Bool
  completedRuns : Nat
  deriving Repr

def boundaryRefusalStop : StopRule ExperimentTrace where
  name := "boundary-refusal"
  fires := fun trace => trace.boundaryRefused = true
  check := fun trace => trace.boundaryRefused
  check_iff := fun _ => Iff.rfl

def budgetCapStop : StopRule ExperimentTrace where
  name := "budget-cap"
  fires := fun trace => 4 ≤ trace.completedRuns
  check := fun trace => decide (4 ≤ trace.completedRuns)
  check_iff := fun trace => by simp

def decisionRule : DecisionRule ExperimentTrace Outcome where
  name := "nonseedable-pilot-fixture-decision"
  classify := fun trace => match trace.classification with
    | TraceClass.complete => Outcome.accept
    | TraceClass.invalid => Outcome.reject

def identityFloorEndpoint : NamedEndpoint where
  name := "identity-floor"
  nameNonempty := by decide

inductive ProblemId where
  | problemAlpha
  deriving DecidableEq, Repr

def pilotUnitIds : List ProblemId := [
  .problemAlpha,
]

def replicationPlan := ReplicationPlan.pilot
  pilotUnitIds (by decide)
  (VariationPlan.measured identityFloorEndpoint)

noncomputable def baseRegistration : Registration ExperimentTrace where
  name := "nonseedable-pilot-fixture"
  claim := ClaimForm.comparative
  arms := [controlArm, withoutMemoryArm]
  flags := []
  estimatedCost := 4
  budgetCap := 4
  teardownDeadline := some 1

/-- The concrete teardown commitment retained alongside the existing
`Registration.teardownDeadline` marker. -/
def teardownCommitment : String := "retain the fixture receipt and delete its temporary worktree"

noncomputable def prospectiveRegistration :
    ProspectiveRegistration ProblemId ExperimentTrace Outcome where
  base := baseRegistration
  replication := replicationPlan
  stopRules := [boundaryRefusalStop, budgetCapStop]
  stopRulesNonempty := by simp
  decision := decisionRule

def readinessEvidence : Evidence where
  toolchainExercised := true
  codeIdentityAsserted := true
  teardownExercised := true
  armsShownDistinct := true

def readinessSmoke : ExperimentTrace where
  classification := TraceClass.complete
  boundaryRefused := false
  completedRuns := 0

noncomputable def baseReadyToRun :
    ReadyToRun baseRegistration readinessEvidence readinessSmoke where
  apparatus := by simp [Evidence.apparatusSound, readinessEvidence]
  discharged := by
    intro o ho
    simp [Registration.obligations, baseRegistration, controlArm, withoutMemoryArm] at ho
    rcases ho with (rfl | rfl | h)
    · exact memoryAxis_navigable
    · rfl
    · rcases h with (rfl | rfl)
      · norm_num [Discharged, baseRegistration]
      · rfl

noncomputable def prospectiveReadyToRun :
    ProspectiveReadyToRun prospectiveRegistration readinessEvidence readinessSmoke where
  baseReady := by simpa [prospectiveRegistration] using baseReadyToRun
  smokeClear := by
    intro s hs
    have h : s = boundaryRefusalStop ∨ s = budgetCapStop := by
      simpa [prospectiveRegistration] using hs
    rcases h with (rfl | rfl)
    · rfl
    · rfl

example : prospectiveRegistration.stopRules ≠ [] := by decide
example : prospectiveRegistration.replication.stage = RegistrationStage.pilot := rfl

end CLeanExperiment_nonseedable_pilot_fixture

end DarkTower
