import Mathlib
import DarkTower.TypedHole
import DarkTower.Comb
import DarkTower.Discharge
import DarkTower.BV
import DarkTower.ExperimentPreregistration
import DarkTower.ExperimentalDesign

/-!
# CLean experiments as prospective DarkTower registrations

Generated by `futon6/scripts/clean_to_lean.py` from an experiment-shaped CLean
EDN. The EDN is the authority: axes, arms, complete seed triples, stop rules,
and the total decision function below are all rendered from it.
-/

namespace DarkTower
open CategoryTheory

namespace CLeanProof_r0_discriminating_environment
-- r0-discriminating-environment: Does epistemic-ablation identity fall when exploration becomes valuable?

/-- The iching/CT method tags appearing in this proof's spine. -/
inductive Method where
  | freezeFactorialDesign
  | verifyMechanismPreconditions
  | verifyPositiveControl
  | measureIdentity
  | adjudicate
  deriving DecidableEq, Repr

/-- The pattern-tagged method spine (the informal reading), a BV.seq chain. -/
def spine : BV Method :=
  BV.seq (BV.atom Method.freezeFactorialDesign) (BV.seq (BV.atom Method.verifyMechanismPreconditions) (BV.seq (BV.atom Method.verifyPositiveControl) (BV.seq (BV.atom Method.measureIdentity) (BV.atom Method.adjudicate))))

/-- The proof steps (the comb positions). -/
inductive Stp where
  | e1
  | e2
  | e3
  | e4
  | e5
  deriving DecidableEq, Repr

/-- The direction a still-open typed hole exposes: an outstanding proof. -/
inductive Obligation where
  | proof
  deriving DecidableEq, Repr

/-- The typed-hole interface: each step is a position; a step exposes an
    `Obligation` iff it carries an open hole, else `Empty` (discharged). -/
def holes : TypedHole where
  poly :=
    { A := Stp
      B := fun
        | Stp.e1 => Empty
        | Stp.e2 => Empty
        | Stp.e3 => Obligation
        | Stp.e4 => Empty
        | Stp.e5 => Empty
    }
  satiety := fun
    | Stp.e1 => SatietyGrade.canon
    | Stp.e2 => SatietyGrade.canon
    | Stp.e3 => SatietyGrade.canon
    | Stp.e4 => SatietyGrade.canon
    | Stp.e5 => SatietyGrade.canon

/-- Named results the reduce-to-known steps discharge to. -/
inductive KnownResult where
  | decisionRule
  deriving DecidableEq, Repr

/-- Which steps discharge to a named theorem (carry no open hole). -/
def discharges : Stp -> Option KnownResult
  | Stp.e5 => some KnownResult.decisionRule
  | _ => none

/-- The comb wiring (construct -> consume edges). -/
def wires : List (Stp × Stp) := [(Stp.e1, Stp.e2), (Stp.e2, Stp.e3), (Stp.e3, Stp.e4), (Stp.e4, Stp.e5)]

/-- The readings held together (M-typed-holes copar): informal ∥ formal ∥ executable. -/
inductive Reading where
  | informal
  | formal
  | executable
  deriving DecidableEq, Repr
def readings : BV Reading :=
  BV.copar (BV.atom Reading.informal) (BV.copar (BV.atom Reading.formal) (BV.atom Reading.executable))

-- Self-verifying checks: the experiment pipeline is type-correct and computes.
example : holes.holeType Stp.e1 = Empty := rfl
example : holes.holeType Stp.e2 = Empty := rfl
example : holes.holeType Stp.e3 = Obligation := rfl
example : holes.holeType Stp.e4 = Empty := rfl
example : holes.holeType Stp.e5 = Empty := rfl
example : holes.satiety Stp.e1 = SatietyGrade.canon := rfl
example : holes.satiety Stp.e2 = SatietyGrade.canon := rfl
example : holes.satiety Stp.e3 = SatietyGrade.canon := rfl
example : holes.satiety Stp.e4 = SatietyGrade.canon := rfl
example : holes.satiety Stp.e5 = SatietyGrade.canon := rfl
example : discharges Stp.e5 = some KnownResult.decisionRule := rfl
/-- The spine prefix reassociates by BV structural congruence (well-shaped comb). -/
example : BV.Cong
    (BV.seq (BV.seq (BV.atom Method.freezeFactorialDesign) (BV.atom Method.verifyMechanismPreconditions)) (BV.atom Method.verifyPositiveControl))
    (BV.seq (BV.atom Method.freezeFactorialDesign) (BV.seq (BV.atom Method.verifyMechanismPreconditions) (BV.atom Method.verifyPositiveControl))) :=
  BV.Cong.seq_assoc (BV.atom Method.freezeFactorialDesign) (BV.atom Method.verifyMechanismPreconditions) (BV.atom Method.verifyPositiveControl)
/-- The informal ∥ formal copar reading commutes (one object, its readings). -/
example : BV.Cong (BV.copar (BV.atom Reading.informal) (BV.atom Reading.formal)) (BV.copar (BV.atom Reading.formal) (BV.atom Reading.informal)) :=
  BV.Cong.copar_comm (BV.atom Reading.informal) (BV.atom Reading.formal)

end CLeanProof_r0_discriminating_environment

namespace CLeanExperiment_r0_discriminating_environment
-- r0-discriminating-environment: Does epistemic-ablation identity fall when exploration becomes valuable?

open ExperimentPreregistration
open ExperimentalDesign

inductive Scenario where
  | patchy
  | sparse
  | snowdrift
  deriving DecidableEq, Repr

structure SeedTriple where
  scenario : Scenario
  run : Nat
  food : Nat
  movement : Nat
  choice : Nat
  deriving DecidableEq, Repr

def pilotSeedTriples : List SeedTriple := [
  { scenario := Scenario.patchy, run := 1, food := 202608110, movement := 202608111, choice := 202658110 },
  { scenario := Scenario.patchy, run := 2, food := 202608112, movement := 202608113, choice := 202658111 },
  { scenario := Scenario.patchy, run := 3, food := 202608114, movement := 202608115, choice := 202658112 },
  { scenario := Scenario.patchy, run := 4, food := 202608116, movement := 202608117, choice := 202658113 },
  { scenario := Scenario.patchy, run := 5, food := 202608118, movement := 202608119, choice := 202658114 },
  { scenario := Scenario.patchy, run := 6, food := 202608120, movement := 202608121, choice := 202658115 },
  { scenario := Scenario.patchy, run := 7, food := 202608122, movement := 202608123, choice := 202658116 },
  { scenario := Scenario.patchy, run := 8, food := 202608124, movement := 202608125, choice := 202658117 },
  { scenario := Scenario.patchy, run := 9, food := 202608126, movement := 202608127, choice := 202658118 },
  { scenario := Scenario.patchy, run := 10, food := 202608128, movement := 202608129, choice := 202658119 },
  { scenario := Scenario.patchy, run := 11, food := 202608130, movement := 202608131, choice := 202658120 },
  { scenario := Scenario.patchy, run := 12, food := 202608132, movement := 202608133, choice := 202658121 },
  { scenario := Scenario.patchy, run := 13, food := 202608134, movement := 202608135, choice := 202658122 },
  { scenario := Scenario.patchy, run := 14, food := 202608136, movement := 202608137, choice := 202658123 },
  { scenario := Scenario.patchy, run := 15, food := 202608138, movement := 202608139, choice := 202658124 },
  { scenario := Scenario.patchy, run := 16, food := 202608140, movement := 202608141, choice := 202658125 },
  { scenario := Scenario.patchy, run := 17, food := 202608142, movement := 202608143, choice := 202658126 },
  { scenario := Scenario.patchy, run := 18, food := 202608144, movement := 202608145, choice := 202658127 },
  { scenario := Scenario.patchy, run := 19, food := 202608146, movement := 202608147, choice := 202658128 },
  { scenario := Scenario.patchy, run := 20, food := 202608148, movement := 202608149, choice := 202658129 },
  { scenario := Scenario.patchy, run := 21, food := 202608150, movement := 202608151, choice := 202658130 },
  { scenario := Scenario.patchy, run := 22, food := 202608152, movement := 202608153, choice := 202658131 },
  { scenario := Scenario.patchy, run := 23, food := 202608154, movement := 202608155, choice := 202658132 },
  { scenario := Scenario.patchy, run := 24, food := 202608156, movement := 202608157, choice := 202658133 },
  { scenario := Scenario.patchy, run := 25, food := 202608158, movement := 202608159, choice := 202658134 },
  { scenario := Scenario.patchy, run := 26, food := 202608160, movement := 202608161, choice := 202658135 },
  { scenario := Scenario.patchy, run := 27, food := 202608162, movement := 202608163, choice := 202658136 },
  { scenario := Scenario.patchy, run := 28, food := 202608164, movement := 202608165, choice := 202658137 },
  { scenario := Scenario.patchy, run := 29, food := 202608166, movement := 202608167, choice := 202658138 },
  { scenario := Scenario.patchy, run := 30, food := 202608168, movement := 202608169, choice := 202658139 },
  { scenario := Scenario.sparse, run := 1, food := 202708110, movement := 202708111, choice := 202758110 },
  { scenario := Scenario.sparse, run := 2, food := 202708112, movement := 202708113, choice := 202758111 },
  { scenario := Scenario.sparse, run := 3, food := 202708114, movement := 202708115, choice := 202758112 },
  { scenario := Scenario.sparse, run := 4, food := 202708116, movement := 202708117, choice := 202758113 },
  { scenario := Scenario.sparse, run := 5, food := 202708118, movement := 202708119, choice := 202758114 },
  { scenario := Scenario.sparse, run := 6, food := 202708120, movement := 202708121, choice := 202758115 },
  { scenario := Scenario.sparse, run := 7, food := 202708122, movement := 202708123, choice := 202758116 },
  { scenario := Scenario.sparse, run := 8, food := 202708124, movement := 202708125, choice := 202758117 },
  { scenario := Scenario.sparse, run := 9, food := 202708126, movement := 202708127, choice := 202758118 },
  { scenario := Scenario.sparse, run := 10, food := 202708128, movement := 202708129, choice := 202758119 },
  { scenario := Scenario.sparse, run := 11, food := 202708130, movement := 202708131, choice := 202758120 },
  { scenario := Scenario.sparse, run := 12, food := 202708132, movement := 202708133, choice := 202758121 },
  { scenario := Scenario.sparse, run := 13, food := 202708134, movement := 202708135, choice := 202758122 },
  { scenario := Scenario.sparse, run := 14, food := 202708136, movement := 202708137, choice := 202758123 },
  { scenario := Scenario.sparse, run := 15, food := 202708138, movement := 202708139, choice := 202758124 },
  { scenario := Scenario.sparse, run := 16, food := 202708140, movement := 202708141, choice := 202758125 },
  { scenario := Scenario.sparse, run := 17, food := 202708142, movement := 202708143, choice := 202758126 },
  { scenario := Scenario.sparse, run := 18, food := 202708144, movement := 202708145, choice := 202758127 },
  { scenario := Scenario.sparse, run := 19, food := 202708146, movement := 202708147, choice := 202758128 },
  { scenario := Scenario.sparse, run := 20, food := 202708148, movement := 202708149, choice := 202758129 },
  { scenario := Scenario.sparse, run := 21, food := 202708150, movement := 202708151, choice := 202758130 },
  { scenario := Scenario.sparse, run := 22, food := 202708152, movement := 202708153, choice := 202758131 },
  { scenario := Scenario.sparse, run := 23, food := 202708154, movement := 202708155, choice := 202758132 },
  { scenario := Scenario.sparse, run := 24, food := 202708156, movement := 202708157, choice := 202758133 },
  { scenario := Scenario.sparse, run := 25, food := 202708158, movement := 202708159, choice := 202758134 },
  { scenario := Scenario.sparse, run := 26, food := 202708160, movement := 202708161, choice := 202758135 },
  { scenario := Scenario.sparse, run := 27, food := 202708162, movement := 202708163, choice := 202758136 },
  { scenario := Scenario.sparse, run := 28, food := 202708164, movement := 202708165, choice := 202758137 },
  { scenario := Scenario.sparse, run := 29, food := 202708166, movement := 202708167, choice := 202758138 },
  { scenario := Scenario.sparse, run := 30, food := 202708168, movement := 202708169, choice := 202758139 },
  { scenario := Scenario.snowdrift, run := 1, food := 202808110, movement := 202808111, choice := 202858110 },
  { scenario := Scenario.snowdrift, run := 2, food := 202808112, movement := 202808113, choice := 202858111 },
  { scenario := Scenario.snowdrift, run := 3, food := 202808114, movement := 202808115, choice := 202858112 },
  { scenario := Scenario.snowdrift, run := 4, food := 202808116, movement := 202808117, choice := 202858113 },
  { scenario := Scenario.snowdrift, run := 5, food := 202808118, movement := 202808119, choice := 202858114 },
  { scenario := Scenario.snowdrift, run := 6, food := 202808120, movement := 202808121, choice := 202858115 },
  { scenario := Scenario.snowdrift, run := 7, food := 202808122, movement := 202808123, choice := 202858116 },
  { scenario := Scenario.snowdrift, run := 8, food := 202808124, movement := 202808125, choice := 202858117 },
  { scenario := Scenario.snowdrift, run := 9, food := 202808126, movement := 202808127, choice := 202858118 },
  { scenario := Scenario.snowdrift, run := 10, food := 202808128, movement := 202808129, choice := 202858119 },
  { scenario := Scenario.snowdrift, run := 11, food := 202808130, movement := 202808131, choice := 202858120 },
  { scenario := Scenario.snowdrift, run := 12, food := 202808132, movement := 202808133, choice := 202858121 },
  { scenario := Scenario.snowdrift, run := 13, food := 202808134, movement := 202808135, choice := 202858122 },
  { scenario := Scenario.snowdrift, run := 14, food := 202808136, movement := 202808137, choice := 202858123 },
  { scenario := Scenario.snowdrift, run := 15, food := 202808138, movement := 202808139, choice := 202858124 },
  { scenario := Scenario.snowdrift, run := 16, food := 202808140, movement := 202808141, choice := 202858125 },
  { scenario := Scenario.snowdrift, run := 17, food := 202808142, movement := 202808143, choice := 202858126 },
  { scenario := Scenario.snowdrift, run := 18, food := 202808144, movement := 202808145, choice := 202858127 },
  { scenario := Scenario.snowdrift, run := 19, food := 202808146, movement := 202808147, choice := 202858128 },
  { scenario := Scenario.snowdrift, run := 20, food := 202808148, movement := 202808149, choice := 202858129 },
  { scenario := Scenario.snowdrift, run := 21, food := 202808150, movement := 202808151, choice := 202858130 },
  { scenario := Scenario.snowdrift, run := 22, food := 202808152, movement := 202808153, choice := 202858131 },
  { scenario := Scenario.snowdrift, run := 23, food := 202808154, movement := 202808155, choice := 202858132 },
  { scenario := Scenario.snowdrift, run := 24, food := 202808156, movement := 202808157, choice := 202858133 },
  { scenario := Scenario.snowdrift, run := 25, food := 202808158, movement := 202808159, choice := 202858134 },
  { scenario := Scenario.snowdrift, run := 26, food := 202808160, movement := 202808161, choice := 202858135 },
  { scenario := Scenario.snowdrift, run := 27, food := 202808162, movement := 202808163, choice := 202858136 },
  { scenario := Scenario.snowdrift, run := 28, food := 202808164, movement := 202808165, choice := 202858137 },
  { scenario := Scenario.snowdrift, run := 29, food := 202808166, movement := 202808167, choice := 202858138 },
  { scenario := Scenario.snowdrift, run := 30, food := 202808168, movement := 202808169, choice := 202858139 }
]

def confirmationSeedTriples : List SeedTriple := [
  { scenario := Scenario.patchy, run := 1, food := 202610110, movement := 202610111, choice := 202660110 },
  { scenario := Scenario.patchy, run := 2, food := 202610112, movement := 202610113, choice := 202660111 },
  { scenario := Scenario.patchy, run := 3, food := 202610114, movement := 202610115, choice := 202660112 },
  { scenario := Scenario.patchy, run := 4, food := 202610116, movement := 202610117, choice := 202660113 },
  { scenario := Scenario.patchy, run := 5, food := 202610118, movement := 202610119, choice := 202660114 },
  { scenario := Scenario.patchy, run := 6, food := 202610120, movement := 202610121, choice := 202660115 },
  { scenario := Scenario.patchy, run := 7, food := 202610122, movement := 202610123, choice := 202660116 },
  { scenario := Scenario.patchy, run := 8, food := 202610124, movement := 202610125, choice := 202660117 },
  { scenario := Scenario.patchy, run := 9, food := 202610126, movement := 202610127, choice := 202660118 },
  { scenario := Scenario.patchy, run := 10, food := 202610128, movement := 202610129, choice := 202660119 },
  { scenario := Scenario.patchy, run := 11, food := 202610130, movement := 202610131, choice := 202660120 },
  { scenario := Scenario.patchy, run := 12, food := 202610132, movement := 202610133, choice := 202660121 },
  { scenario := Scenario.patchy, run := 13, food := 202610134, movement := 202610135, choice := 202660122 },
  { scenario := Scenario.patchy, run := 14, food := 202610136, movement := 202610137, choice := 202660123 },
  { scenario := Scenario.patchy, run := 15, food := 202610138, movement := 202610139, choice := 202660124 },
  { scenario := Scenario.patchy, run := 16, food := 202610140, movement := 202610141, choice := 202660125 },
  { scenario := Scenario.patchy, run := 17, food := 202610142, movement := 202610143, choice := 202660126 },
  { scenario := Scenario.patchy, run := 18, food := 202610144, movement := 202610145, choice := 202660127 },
  { scenario := Scenario.patchy, run := 19, food := 202610146, movement := 202610147, choice := 202660128 },
  { scenario := Scenario.patchy, run := 20, food := 202610148, movement := 202610149, choice := 202660129 },
  { scenario := Scenario.patchy, run := 21, food := 202610150, movement := 202610151, choice := 202660130 },
  { scenario := Scenario.patchy, run := 22, food := 202610152, movement := 202610153, choice := 202660131 },
  { scenario := Scenario.patchy, run := 23, food := 202610154, movement := 202610155, choice := 202660132 },
  { scenario := Scenario.patchy, run := 24, food := 202610156, movement := 202610157, choice := 202660133 },
  { scenario := Scenario.patchy, run := 25, food := 202610158, movement := 202610159, choice := 202660134 },
  { scenario := Scenario.patchy, run := 26, food := 202610160, movement := 202610161, choice := 202660135 },
  { scenario := Scenario.patchy, run := 27, food := 202610162, movement := 202610163, choice := 202660136 },
  { scenario := Scenario.patchy, run := 28, food := 202610164, movement := 202610165, choice := 202660137 },
  { scenario := Scenario.patchy, run := 29, food := 202610166, movement := 202610167, choice := 202660138 },
  { scenario := Scenario.patchy, run := 30, food := 202610168, movement := 202610169, choice := 202660139 },
  { scenario := Scenario.sparse, run := 1, food := 202710110, movement := 202710111, choice := 202760110 },
  { scenario := Scenario.sparse, run := 2, food := 202710112, movement := 202710113, choice := 202760111 },
  { scenario := Scenario.sparse, run := 3, food := 202710114, movement := 202710115, choice := 202760112 },
  { scenario := Scenario.sparse, run := 4, food := 202710116, movement := 202710117, choice := 202760113 },
  { scenario := Scenario.sparse, run := 5, food := 202710118, movement := 202710119, choice := 202760114 },
  { scenario := Scenario.sparse, run := 6, food := 202710120, movement := 202710121, choice := 202760115 },
  { scenario := Scenario.sparse, run := 7, food := 202710122, movement := 202710123, choice := 202760116 },
  { scenario := Scenario.sparse, run := 8, food := 202710124, movement := 202710125, choice := 202760117 },
  { scenario := Scenario.sparse, run := 9, food := 202710126, movement := 202710127, choice := 202760118 },
  { scenario := Scenario.sparse, run := 10, food := 202710128, movement := 202710129, choice := 202760119 },
  { scenario := Scenario.sparse, run := 11, food := 202710130, movement := 202710131, choice := 202760120 },
  { scenario := Scenario.sparse, run := 12, food := 202710132, movement := 202710133, choice := 202760121 },
  { scenario := Scenario.sparse, run := 13, food := 202710134, movement := 202710135, choice := 202760122 },
  { scenario := Scenario.sparse, run := 14, food := 202710136, movement := 202710137, choice := 202760123 },
  { scenario := Scenario.sparse, run := 15, food := 202710138, movement := 202710139, choice := 202760124 },
  { scenario := Scenario.sparse, run := 16, food := 202710140, movement := 202710141, choice := 202760125 },
  { scenario := Scenario.sparse, run := 17, food := 202710142, movement := 202710143, choice := 202760126 },
  { scenario := Scenario.sparse, run := 18, food := 202710144, movement := 202710145, choice := 202760127 },
  { scenario := Scenario.sparse, run := 19, food := 202710146, movement := 202710147, choice := 202760128 },
  { scenario := Scenario.sparse, run := 20, food := 202710148, movement := 202710149, choice := 202760129 },
  { scenario := Scenario.sparse, run := 21, food := 202710150, movement := 202710151, choice := 202760130 },
  { scenario := Scenario.sparse, run := 22, food := 202710152, movement := 202710153, choice := 202760131 },
  { scenario := Scenario.sparse, run := 23, food := 202710154, movement := 202710155, choice := 202760132 },
  { scenario := Scenario.sparse, run := 24, food := 202710156, movement := 202710157, choice := 202760133 },
  { scenario := Scenario.sparse, run := 25, food := 202710158, movement := 202710159, choice := 202760134 },
  { scenario := Scenario.sparse, run := 26, food := 202710160, movement := 202710161, choice := 202760135 },
  { scenario := Scenario.sparse, run := 27, food := 202710162, movement := 202710163, choice := 202760136 },
  { scenario := Scenario.sparse, run := 28, food := 202710164, movement := 202710165, choice := 202760137 },
  { scenario := Scenario.sparse, run := 29, food := 202710166, movement := 202710167, choice := 202760138 },
  { scenario := Scenario.sparse, run := 30, food := 202710168, movement := 202710169, choice := 202760139 },
  { scenario := Scenario.snowdrift, run := 1, food := 202810110, movement := 202810111, choice := 202860110 },
  { scenario := Scenario.snowdrift, run := 2, food := 202810112, movement := 202810113, choice := 202860111 },
  { scenario := Scenario.snowdrift, run := 3, food := 202810114, movement := 202810115, choice := 202860112 },
  { scenario := Scenario.snowdrift, run := 4, food := 202810116, movement := 202810117, choice := 202860113 },
  { scenario := Scenario.snowdrift, run := 5, food := 202810118, movement := 202810119, choice := 202860114 },
  { scenario := Scenario.snowdrift, run := 6, food := 202810120, movement := 202810121, choice := 202860115 },
  { scenario := Scenario.snowdrift, run := 7, food := 202810122, movement := 202810123, choice := 202860116 },
  { scenario := Scenario.snowdrift, run := 8, food := 202810124, movement := 202810125, choice := 202860117 },
  { scenario := Scenario.snowdrift, run := 9, food := 202810126, movement := 202810127, choice := 202860118 },
  { scenario := Scenario.snowdrift, run := 10, food := 202810128, movement := 202810129, choice := 202860119 },
  { scenario := Scenario.snowdrift, run := 11, food := 202810130, movement := 202810131, choice := 202860120 },
  { scenario := Scenario.snowdrift, run := 12, food := 202810132, movement := 202810133, choice := 202860121 },
  { scenario := Scenario.snowdrift, run := 13, food := 202810134, movement := 202810135, choice := 202860122 },
  { scenario := Scenario.snowdrift, run := 14, food := 202810136, movement := 202810137, choice := 202860123 },
  { scenario := Scenario.snowdrift, run := 15, food := 202810138, movement := 202810139, choice := 202860124 },
  { scenario := Scenario.snowdrift, run := 16, food := 202810140, movement := 202810141, choice := 202860125 },
  { scenario := Scenario.snowdrift, run := 17, food := 202810142, movement := 202810143, choice := 202860126 },
  { scenario := Scenario.snowdrift, run := 18, food := 202810144, movement := 202810145, choice := 202860127 },
  { scenario := Scenario.snowdrift, run := 19, food := 202810146, movement := 202810147, choice := 202860128 },
  { scenario := Scenario.snowdrift, run := 20, food := 202810148, movement := 202810149, choice := 202860129 },
  { scenario := Scenario.snowdrift, run := 21, food := 202810150, movement := 202810151, choice := 202860130 },
  { scenario := Scenario.snowdrift, run := 22, food := 202810152, movement := 202810153, choice := 202860131 },
  { scenario := Scenario.snowdrift, run := 23, food := 202810154, movement := 202810155, choice := 202860132 },
  { scenario := Scenario.snowdrift, run := 24, food := 202810156, movement := 202810157, choice := 202860133 },
  { scenario := Scenario.snowdrift, run := 25, food := 202810158, movement := 202810159, choice := 202860134 },
  { scenario := Scenario.snowdrift, run := 26, food := 202810160, movement := 202810161, choice := 202860135 },
  { scenario := Scenario.snowdrift, run := 27, food := 202810162, movement := 202810163, choice := 202860136 },
  { scenario := Scenario.snowdrift, run := 28, food := 202810164, movement := 202810165, choice := 202860137 },
  { scenario := Scenario.snowdrift, run := 29, food := 202810166, movement := 202810167, choice := 202860138 },
  { scenario := Scenario.snowdrift, run := 30, food := 202810168, movement := 202810169, choice := 202860139 }
]

def priorConfirmationSeedTriples : List SeedTriple := [
  { scenario := Scenario.patchy, run := 1, food := 202609110, movement := 202609111, choice := 202659110 },
  { scenario := Scenario.patchy, run := 2, food := 202609112, movement := 202609113, choice := 202659111 },
  { scenario := Scenario.patchy, run := 3, food := 202609114, movement := 202609115, choice := 202659112 },
  { scenario := Scenario.patchy, run := 4, food := 202609116, movement := 202609117, choice := 202659113 },
  { scenario := Scenario.patchy, run := 5, food := 202609118, movement := 202609119, choice := 202659114 },
  { scenario := Scenario.patchy, run := 6, food := 202609120, movement := 202609121, choice := 202659115 },
  { scenario := Scenario.patchy, run := 7, food := 202609122, movement := 202609123, choice := 202659116 },
  { scenario := Scenario.patchy, run := 8, food := 202609124, movement := 202609125, choice := 202659117 },
  { scenario := Scenario.patchy, run := 9, food := 202609126, movement := 202609127, choice := 202659118 },
  { scenario := Scenario.patchy, run := 10, food := 202609128, movement := 202609129, choice := 202659119 },
  { scenario := Scenario.patchy, run := 11, food := 202609130, movement := 202609131, choice := 202659120 },
  { scenario := Scenario.patchy, run := 12, food := 202609132, movement := 202609133, choice := 202659121 },
  { scenario := Scenario.patchy, run := 13, food := 202609134, movement := 202609135, choice := 202659122 },
  { scenario := Scenario.patchy, run := 14, food := 202609136, movement := 202609137, choice := 202659123 },
  { scenario := Scenario.patchy, run := 15, food := 202609138, movement := 202609139, choice := 202659124 },
  { scenario := Scenario.patchy, run := 16, food := 202609140, movement := 202609141, choice := 202659125 },
  { scenario := Scenario.patchy, run := 17, food := 202609142, movement := 202609143, choice := 202659126 },
  { scenario := Scenario.patchy, run := 18, food := 202609144, movement := 202609145, choice := 202659127 },
  { scenario := Scenario.patchy, run := 19, food := 202609146, movement := 202609147, choice := 202659128 },
  { scenario := Scenario.patchy, run := 20, food := 202609148, movement := 202609149, choice := 202659129 },
  { scenario := Scenario.patchy, run := 21, food := 202609150, movement := 202609151, choice := 202659130 },
  { scenario := Scenario.patchy, run := 22, food := 202609152, movement := 202609153, choice := 202659131 },
  { scenario := Scenario.patchy, run := 23, food := 202609154, movement := 202609155, choice := 202659132 },
  { scenario := Scenario.patchy, run := 24, food := 202609156, movement := 202609157, choice := 202659133 },
  { scenario := Scenario.patchy, run := 25, food := 202609158, movement := 202609159, choice := 202659134 },
  { scenario := Scenario.patchy, run := 26, food := 202609160, movement := 202609161, choice := 202659135 },
  { scenario := Scenario.patchy, run := 27, food := 202609162, movement := 202609163, choice := 202659136 },
  { scenario := Scenario.patchy, run := 28, food := 202609164, movement := 202609165, choice := 202659137 },
  { scenario := Scenario.patchy, run := 29, food := 202609166, movement := 202609167, choice := 202659138 },
  { scenario := Scenario.patchy, run := 30, food := 202609168, movement := 202609169, choice := 202659139 },
  { scenario := Scenario.sparse, run := 1, food := 202709110, movement := 202709111, choice := 202759110 },
  { scenario := Scenario.sparse, run := 2, food := 202709112, movement := 202709113, choice := 202759111 },
  { scenario := Scenario.sparse, run := 3, food := 202709114, movement := 202709115, choice := 202759112 },
  { scenario := Scenario.sparse, run := 4, food := 202709116, movement := 202709117, choice := 202759113 },
  { scenario := Scenario.sparse, run := 5, food := 202709118, movement := 202709119, choice := 202759114 },
  { scenario := Scenario.sparse, run := 6, food := 202709120, movement := 202709121, choice := 202759115 },
  { scenario := Scenario.sparse, run := 7, food := 202709122, movement := 202709123, choice := 202759116 },
  { scenario := Scenario.sparse, run := 8, food := 202709124, movement := 202709125, choice := 202759117 },
  { scenario := Scenario.sparse, run := 9, food := 202709126, movement := 202709127, choice := 202759118 },
  { scenario := Scenario.sparse, run := 10, food := 202709128, movement := 202709129, choice := 202759119 },
  { scenario := Scenario.sparse, run := 11, food := 202709130, movement := 202709131, choice := 202759120 },
  { scenario := Scenario.sparse, run := 12, food := 202709132, movement := 202709133, choice := 202759121 },
  { scenario := Scenario.sparse, run := 13, food := 202709134, movement := 202709135, choice := 202759122 },
  { scenario := Scenario.sparse, run := 14, food := 202709136, movement := 202709137, choice := 202759123 },
  { scenario := Scenario.sparse, run := 15, food := 202709138, movement := 202709139, choice := 202759124 },
  { scenario := Scenario.sparse, run := 16, food := 202709140, movement := 202709141, choice := 202759125 },
  { scenario := Scenario.sparse, run := 17, food := 202709142, movement := 202709143, choice := 202759126 },
  { scenario := Scenario.sparse, run := 18, food := 202709144, movement := 202709145, choice := 202759127 },
  { scenario := Scenario.sparse, run := 19, food := 202709146, movement := 202709147, choice := 202759128 },
  { scenario := Scenario.sparse, run := 20, food := 202709148, movement := 202709149, choice := 202759129 },
  { scenario := Scenario.sparse, run := 21, food := 202709150, movement := 202709151, choice := 202759130 },
  { scenario := Scenario.sparse, run := 22, food := 202709152, movement := 202709153, choice := 202759131 },
  { scenario := Scenario.sparse, run := 23, food := 202709154, movement := 202709155, choice := 202759132 },
  { scenario := Scenario.sparse, run := 24, food := 202709156, movement := 202709157, choice := 202759133 },
  { scenario := Scenario.sparse, run := 25, food := 202709158, movement := 202709159, choice := 202759134 },
  { scenario := Scenario.sparse, run := 26, food := 202709160, movement := 202709161, choice := 202759135 },
  { scenario := Scenario.sparse, run := 27, food := 202709162, movement := 202709163, choice := 202759136 },
  { scenario := Scenario.sparse, run := 28, food := 202709164, movement := 202709165, choice := 202759137 },
  { scenario := Scenario.sparse, run := 29, food := 202709166, movement := 202709167, choice := 202759138 },
  { scenario := Scenario.sparse, run := 30, food := 202709168, movement := 202709169, choice := 202759139 },
  { scenario := Scenario.snowdrift, run := 1, food := 202809110, movement := 202809111, choice := 202859110 },
  { scenario := Scenario.snowdrift, run := 2, food := 202809112, movement := 202809113, choice := 202859111 },
  { scenario := Scenario.snowdrift, run := 3, food := 202809114, movement := 202809115, choice := 202859112 },
  { scenario := Scenario.snowdrift, run := 4, food := 202809116, movement := 202809117, choice := 202859113 },
  { scenario := Scenario.snowdrift, run := 5, food := 202809118, movement := 202809119, choice := 202859114 },
  { scenario := Scenario.snowdrift, run := 6, food := 202809120, movement := 202809121, choice := 202859115 },
  { scenario := Scenario.snowdrift, run := 7, food := 202809122, movement := 202809123, choice := 202859116 },
  { scenario := Scenario.snowdrift, run := 8, food := 202809124, movement := 202809125, choice := 202859117 },
  { scenario := Scenario.snowdrift, run := 9, food := 202809126, movement := 202809127, choice := 202859118 },
  { scenario := Scenario.snowdrift, run := 10, food := 202809128, movement := 202809129, choice := 202859119 },
  { scenario := Scenario.snowdrift, run := 11, food := 202809130, movement := 202809131, choice := 202859120 },
  { scenario := Scenario.snowdrift, run := 12, food := 202809132, movement := 202809133, choice := 202859121 },
  { scenario := Scenario.snowdrift, run := 13, food := 202809134, movement := 202809135, choice := 202859122 },
  { scenario := Scenario.snowdrift, run := 14, food := 202809136, movement := 202809137, choice := 202859123 },
  { scenario := Scenario.snowdrift, run := 15, food := 202809138, movement := 202809139, choice := 202859124 },
  { scenario := Scenario.snowdrift, run := 16, food := 202809140, movement := 202809141, choice := 202859125 },
  { scenario := Scenario.snowdrift, run := 17, food := 202809142, movement := 202809143, choice := 202859126 },
  { scenario := Scenario.snowdrift, run := 18, food := 202809144, movement := 202809145, choice := 202859127 },
  { scenario := Scenario.snowdrift, run := 19, food := 202809146, movement := 202809147, choice := 202859128 },
  { scenario := Scenario.snowdrift, run := 20, food := 202809148, movement := 202809149, choice := 202859129 },
  { scenario := Scenario.snowdrift, run := 21, food := 202809150, movement := 202809151, choice := 202859130 },
  { scenario := Scenario.snowdrift, run := 22, food := 202809152, movement := 202809153, choice := 202859131 },
  { scenario := Scenario.snowdrift, run := 23, food := 202809154, movement := 202809155, choice := 202859132 },
  { scenario := Scenario.snowdrift, run := 24, food := 202809156, movement := 202809157, choice := 202859133 },
  { scenario := Scenario.snowdrift, run := 25, food := 202809158, movement := 202809159, choice := 202859134 },
  { scenario := Scenario.snowdrift, run := 26, food := 202809160, movement := 202809161, choice := 202859135 },
  { scenario := Scenario.snowdrift, run := 27, food := 202809162, movement := 202809163, choice := 202859136 },
  { scenario := Scenario.snowdrift, run := 28, food := 202809164, movement := 202809165, choice := 202859137 },
  { scenario := Scenario.snowdrift, run := 29, food := 202809166, movement := 202809167, choice := 202859138 },
  { scenario := Scenario.snowdrift, run := 30, food := 202809168, movement := 202809169, choice := 202859139 }
]

/-- (:var mu) is common to all candidate actions; its ablation cannot alter argmax in any environment -/
noncomputable def canonicalAmbiguityAxis : Axis where
  name := "canonical-ambiguity"
  levels := [0, 1]
  score := fun _ => 0

theorem canonicalAmbiguityAxis_predicted_not_navigable : ¬ canonicalAmbiguityAxis.Navigable :=
  not_navigable_of_constant (fun _ _ => rfl)

/-- action-dependent directed information gain -/
noncomputable def directedEigAxis : Axis where
  name := "directed-eig"
  levels := [0, 1]
  score := fun x => x

theorem directedEigAxis_navigable : directedEigAxis.Navigable := by
  norm_num [Axis.Navigable, Axis.gradientSteps, directedEigAxis]

/-- action-dependent information-gain augmentation -/
noncomputable def infoGainAxis : Axis where
  name := "info-gain"
  levels := [0, 1]
  score := fun x => x

theorem infoGainAxis_navigable : infoGainAxis.Navigable := by
  norm_num [Axis.Navigable, Axis.gradientSteps, infoGainAxis]

/-- action-dependent pragmatic risk -/
noncomputable def klRiskAxis : Axis where
  name := "kl-risk"
  levels := [0, 1]
  score := fun x => x

theorem klRiskAxis_navigable : klRiskAxis.Navigable := by
  norm_num [Axis.Navigable, Axis.gradientSteps, klRiskAxis]

/-- crossed environmental factor manipulating how readily food can be reached without exploration -/
noncomputable def gridScaleAxis : Axis where
  name := "grid-scale"
  levels := [10, 24, 36]
  score := fun x => x

theorem gridScaleAxis_navigable : gridScaleAxis.Navigable := by
  norm_num [Axis.Navigable, Axis.gradientSteps, gridScaleAxis]

noncomputable def aifFullArm : Arm where
  name := "aif-full"
  neutral := false
  axes := []
  role := ArmRole.treatment

noncomputable def noCanonicalAmbiguityArm : Arm where
  name := "no-canonical-ambiguity"
  neutral := false
  axes := [canonicalAmbiguityAxis]
  role := ArmRole.positiveControl

noncomputable def noDirectedEigArm : Arm where
  name := "no-directed-eig"
  neutral := false
  axes := [directedEigAxis]
  role := ArmRole.treatment

noncomputable def noInfoGainArm : Arm where
  name := "no-info-gain"
  neutral := false
  axes := [infoGainAxis]
  role := ArmRole.treatment

noncomputable def noRiskArm : Arm where
  name := "no-risk"
  neutral := false
  axes := [klRiskAxis]
  role := ArmRole.treatment

noncomputable def classicArm : Arm where
  name := "classic"
  neutral := true
  axes := []
  role := ArmRole.baselineNeutral

inductive TraceClass where
  | controlViolated
  | identityPersists
  | identityFalls
  | mixed
  | incomplete
  deriving DecidableEq, Repr

inductive Outcome where
  | abandonedAnalysisInvalid
  | structuralInertnessSurvivesScaling
  | priorInertnessWasEnvironmentConfounded
  | reportGridAndScenarioSpecific
  | notInterpretable
  deriving DecidableEq, Repr

structure ExperimentTrace where
  classification : TraceClass
  positiveControlViolated : Bool
  deriving Repr

def positiveControlViolatedStop : StopRule ExperimentTrace where
  name := "positive-control-violated"
  fires := fun trace => trace.positiveControlViolated = true
  check := fun trace => trace.positiveControlViolated
  check_iff := fun _ => Iff.rfl

def decisionRule : DecisionRule ExperimentTrace Outcome where
  name := "r0-discriminating-environment-decision"
  classify := fun trace => match trace.classification with
    | TraceClass.controlViolated => Outcome.abandonedAnalysisInvalid
    | TraceClass.identityPersists => Outcome.structuralInertnessSurvivesScaling
    | TraceClass.identityFalls => Outcome.priorInertnessWasEnvironmentConfounded
    | TraceClass.mixed => Outcome.reportGridAndScenarioSpecific
    | TraceClass.incomplete => Outcome.notInterpretable

def pilotSeedIds : List Nat :=
  (List.range 3).flatMap (fun s =>
    (List.range 30).map (fun i =>
      202608110 + 100000 * s + 2 * i))

def confirmationSeedIds : List Nat :=
  (List.range 3).flatMap (fun s =>
    (List.range 30).map (fun i =>
      202610110 + 100000 * s + 2 * i))

def priorConfirmationSeedIds : List Nat :=
  (List.range 3).flatMap (fun s =>
    (List.range 30).map (fun i =>
      202609110 + 100000 * s + 2 * i))

theorem seedIds_disjoint : pilotSeedIds.Disjoint confirmationSeedIds := by
  rw [List.disjoint_left]
  intro x hp hc
  simp only [pilotSeedIds, List.mem_flatMap] at hp
  rcases hp with ⟨s, hs, hp⟩
  simp only [List.mem_map] at hp
  rcases hp with ⟨i, hi, rfl⟩
  simp only [confirmationSeedIds, List.mem_flatMap] at hc
  rcases hc with ⟨s', hs', hc⟩
  simp only [List.mem_map] at hc
  rcases hc with ⟨i', hi', heq⟩
  have hs_lt := List.mem_range.mp hs
  have hi_lt := List.mem_range.mp hi
  have hs'_lt := List.mem_range.mp hs'
  have hi'_lt := List.mem_range.mp hi'
  omega

theorem priorConfirmationSeedIds_disjoint :
    priorConfirmationSeedIds.Disjoint confirmationSeedIds := by
  rw [List.disjoint_left]
  intro x hp hc
  simp only [priorConfirmationSeedIds, List.mem_flatMap] at hp
  rcases hp with ⟨s, hs, hp⟩
  simp only [List.mem_map] at hp
  rcases hp with ⟨i, hi, rfl⟩
  simp only [confirmationSeedIds, List.mem_flatMap] at hc
  rcases hc with ⟨s', hs', hc⟩
  simp only [List.mem_map] at hc
  rcases hc with ⟨i', hi', heq⟩
  have hs_lt := List.mem_range.mp hs
  have hi_lt := List.mem_range.mp hi
  have hs'_lt := List.mem_range.mp hs'
  have hi'_lt := List.mem_range.mp hi'
  omega

def replicationPlan : ReplicationPlan where
  pilotSeeds := pilotSeedIds
  confirmationSeeds := confirmationSeedIds
  pilotNonempty := by native_decide
  confirmationNonempty := by native_decide
  disjoint := seedIds_disjoint

noncomputable def baseRegistration : Registration ExperimentTrace where
  name := "r0-discriminating-environment"
  claim := ClaimForm.comparative
  arms := [aifFullArm, noCanonicalAmbiguityArm, noDirectedEigArm, noInfoGainArm, noRiskArm, classicArm]
  flags := []
  estimatedCost := 1620
  budgetCap := 1620
  teardownDeadline := some 1

/-- The concrete teardown commitment retained alongside the existing
`Registration.teardownDeadline` marker. -/
def teardownCommitment : String := "write r0-environment.{edn,md}; never overwrite pilot or confirmation artifacts"

noncomputable def prospectiveRegistration :
    ProspectiveRegistration ExperimentTrace Outcome where
  base := baseRegistration
  replication := replicationPlan
  stopRules := [positiveControlViolatedStop]
  stopRulesNonempty := by simp
  decision := decisionRule

def readinessEvidence : Evidence where
  toolchainExercised := true
  codeIdentityAsserted := true
  teardownExercised := true
  armsShownDistinct := true

def readinessSmoke : ExperimentTrace where
  classification := TraceClass.controlViolated
  positiveControlViolated := false

noncomputable def baseReadyToRun :
    ReadyToRun baseRegistration readinessEvidence readinessSmoke where
  apparatus := by simp [Evidence.apparatusSound, readinessEvidence]
  discharged := by
    intro o ho
    simp [Registration.obligations, baseRegistration, aifFullArm, noCanonicalAmbiguityArm, noDirectedEigArm, noInfoGainArm, noRiskArm, classicArm] at ho
    rcases ho with (rfl | rfl | rfl | rfl | rfl | h)
    · exact canonicalAmbiguityAxis_predicted_not_navigable
    · exact directedEigAxis_navigable
    · exact infoGainAxis_navigable
    · exact klRiskAxis_navigable
    · rfl
    · rcases h with (rfl | rfl)
      · norm_num [Discharged, baseRegistration]
      · rfl

noncomputable def prospectiveReadyToRun :
    ProspectiveReadyToRun prospectiveRegistration readinessEvidence readinessSmoke where
  baseReady := by simpa [prospectiveRegistration] using baseReadyToRun
  smokeClear := by
    intro s hs
    simp only [prospectiveRegistration, List.mem_singleton] at hs
    subst s
    rfl

example : prospectiveRegistration.stopRules ≠ [] := by decide
example : prospectiveRegistration.replication.pilotSeeds.Disjoint
    prospectiveRegistration.replication.confirmationSeeds :=
  replicationPlan.disjoint
example : ¬ canonicalAmbiguityAxis.Navigable := canonicalAmbiguityAxis_predicted_not_navigable

/-- The positive control's dead axis is an explicit prediction, not
an accidentally accepted treatment axis. -/
theorem positiveControl_nonNavigability_registered :
    Obligation.axisPredictedNonNavigable canonicalAmbiguityAxis ∈
      baseRegistration.obligations ∧
      ¬ canonicalAmbiguityAxis.Navigable := by
  constructor
  · exact mem_obligations_axisPredictedNonNavigable
      (a := noCanonicalAmbiguityArm) (by simp [baseRegistration])
      (by simp [noCanonicalAmbiguityArm]) (by simp [noCanonicalAmbiguityArm])
  · exact canonicalAmbiguityAxis_predicted_not_navigable

end CLeanExperiment_r0_discriminating_environment

end DarkTower
