/-
Copyright (c) 2026 Joseph Corneli. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import DarkTower.ExperimentalDesign

/-!
# Slice 0: which exotype lift groups neighbourhoods that behave alike?

An EXOTYPE is 36 bits with a design-pattern shape — LEFT/IF preconditions, EGO/BECAUSE
the operator, RIGHT/HOWEVER risks, NEXT/THEN outcomes, and four phenotype-family bits.
`futon5/src/futon5/hexagram/lift.clj` compresses those to a 6-bit hexagram by
eigendecomposing the 6×6 matrix and taking the signs of its eigenvalues.

The hexagram is a SITUATION KEY, not an operator codebook: it exists so a cell can ask
"is this neighbour's context like mine?" before adopting their practice. Recovering an
operator from six bits would be a lossy round-trip, because EGO already *is* the
operator. So the property under test is whether hexagram classes group neighbourhoods
that BEHAVE alike — not whether they index anything.

## Why the axis is a distance profile

The lift is useful only if it is LOCAL: neighbourhoods a small edit apart should land on
nearby hexagrams, and distant ones should not. So each arm's axis is the profile
"neighbourhood Hamming distance ↦ mean hexagram-line distance". A lift that responds to
its input has gradient along that profile; a lift that hashes is flat at chance.

This is exactly what `Axis.Navigable` tests, and it is why the obligation is stated over
ADJACENT levels: a profile that is flat everywhere but one cliff has distinct values and
is still not something a local rule can follow.

## Measured before registering (claude-11, 2026-08-03)

At Hamming distance 1 the current `:eigen-sign` lift changes a mean of **1.426** of six
lines, against a chance level of 3.00, with 32.9% of single-bit flips changing nothing.
So it is partially local, not a hash. Occupancy is **32 of 64**, which is exactly 2^5:
a real 6×6 built from arbitrary bits is not symmetric, so its eigenvalues come in
complex-conjugate pairs which share a sign, and one of the six bits is degenerate. The
flip histogram's anomalous bump at two lines is the same effect.

`:symmetrised` exists to test that diagnosis: symmetrising forces an all-real spectrum,
so all six signs become independent and occupancy should reach 64.
-/

namespace ExotypeLiftVariant

open ExperimentPreregistration ExperimentalDesign

/-- What a Slice-0 smoke run reports. -/
structure Trace where
  /-- Every variant was actually selected and produced its own output; a variant that
  is parsed and ignored reports success while doing nothing. -/
  variantsDistinct : Bool
  /-- The mandatory `:random` arm was run and reported, not dropped for being boring. -/
  randomControlReported : Bool
  /-- Same seed regenerated byte-identically. -/
  deterministic : Bool
  /-- Occupancy, locality, within/between distance and ratio present for every arm. -/
  tableComplete : Bool
  deriving DecidableEq, Repr

/-- Hamming distances between neighbourhoods at which the profile is measured.

Adjacent entries are what the navigability obligation quantifies over, so these are
deliberately close together at the low end: locality is a claim about SMALL edits, and
a profile sampled only at 1 and 36 could not distinguish a local lift from a hash. -/
def profileLevels : List ℝ := [1, 2, 3, 4, 6, 9, 12, 18]

/-- Chance level: with six independent lines, a hash changes three of them on average. -/
def chanceLines : ℝ := 3

/-- The control's profile. A hash ignores its input's structure, so its expected
line-distance is chance at EVERY neighbourhood distance — the profile is constant. -/
def randomScore : ℝ → ℝ := fun _ => chanceLines

/-- The `:random` arm's axis, whose predicted null is that it carries no gradient. -/
noncomputable def randomAxis : Axis where
  name := "random-lift: neighbourhood distance ↦ hexagram-line distance"
  levels := profileLevels
  score := randomScore
  onViolation := none

/-- The control really is unable to separate: a constant profile is not navigable.

This is the obligation `ArmRole.positiveControl` generates — the predicted null must be
PROVED, not assumed. If a hash of the input separated behaviour, the eigen-lift's
separation would be evidence of nothing. -/
theorem randomAxis_not_navigable : ¬ randomAxis.Navigable := by
  apply not_navigable_of_constant
  intro x y
  rfl

/-- A treatment lift's axis. Its profile is supplied by the run, so navigability is an
obligation the measurement discharges rather than something asserted here. -/
noncomputable def treatmentAxis (variant : String) (profile : ℝ → ℝ) : Axis where
  name := variant ++ ": neighbourhood distance ↦ hexagram-line distance"
  levels := profileLevels
  score := profile
  onViolation := none

/-- The five arms. Four treatments and one positive control.

`:random` is a POSITIVE CONTROL rather than a neutral baseline: the framework then
obliges us to prove it cannot move the treatment, instead of quietly exempting it. -/
noncomputable def eigenSignArm (p : ℝ → ℝ) : Arm where
  name := "eigen-sign (incumbent)"
  neutral := false
  axes := [treatmentAxis "eigen-sign" p]

noncomputable def eigenOrderingArm (p : ℝ → ℝ) : Arm where
  name := "eigen-ordering"
  neutral := false
  axes := [treatmentAxis "eigen-ordering" p]

noncomputable def eigenMagnitudeArm (p : ℝ → ℝ) : Arm where
  name := "eigen-magnitude"
  neutral := false
  axes := [treatmentAxis "eigen-magnitude" p]

noncomputable def symmetrisedArm (p : ℝ → ℝ) : Arm where
  name := "symmetrised (predicts occupancy 64)"
  neutral := false
  axes := [treatmentAxis "symmetrised" p]

noncomputable def randomControlArm : Arm where
  name := "random hash (positive control)"
  neutral := true
  axes := [randomAxis]
  role := .positiveControl

/-- Every variant must be observed to act. This is the flag a unit test cannot replace:
it exercises the path from the keyword through to the lift, which is exactly where a
setting can be parsed, ignored, and reported as applied. -/
def variantsAct : Flag Trace where
  name := "each lift variant selected and produced distinct output"
  observable :=
    { name := "variant selection is causally live, control reported, run deterministic"
      holds := fun t =>
        t.variantsDistinct = true ∧ t.randomControlReported = true ∧
        t.deterministic = true ∧ t.tableComplete = true
      check := fun t =>
        t.variantsDistinct && t.randomControlReported &&
        t.deterministic && t.tableComplete
      check_sound := by
        intro t h
        simpa only [Bool.and_eq_true, and_assoc] using h }

/-- The registration.

`claim := .comparative` is what generates `armsSeparable`, so the experiment cannot
report "the variants agree" as a robustness finding when the treatment was inert. -/
noncomputable def base (pSign pOrder pMag pSym : ℝ → ℝ) : Registration Trace where
  name := "exotype-lift-variant-separation"
  claim := .comparative
  arms := [eigenSignArm pSign, eigenOrderingArm pOrder, eigenMagnitudeArm pMag,
    symmetrisedArm pSym, randomControlArm]
  flags := [variantsAct]
  -- 200 neighbourhoods × 5 variants × a 120-step MetaCA run, in minutes on one core.
  estimatedCost := 30
  budgetCap := 90
  teardownDeadline := some 90

/-- The control's obligation appears in the generated list, and it is the REVERSED one.

Stated as a theorem because the polarity is the whole point: a registration that
declared `:random` a plain baseline would generate `axisNavigable` for it, which is the
opposite of what we mean and would be discharged by the control accidentally working. -/
theorem random_control_obligation_is_reversed (pSign pOrder pMag pSym : ℝ → ℝ) :
    Obligation.axisPredictedNonNavigable randomAxis ∈
      (base pSign pOrder pMag pSym).obligations := by
  simp [base, Registration.obligations, randomControlArm]

/-- A comparative claim always obliges separability. -/
theorem separability_is_obliged (pSign pOrder pMag pSym : ℝ → ℝ) :
    Obligation.armsSeparable ∈ (base pSign pOrder pMag pSym).obligations := by
  simp [base, Registration.obligations]

/-! ## Non-triviality

A registration that generates no obligations would satisfy every theorem above
vacuously while gating nothing. These pin that the declared axes actually produce
work, and that the control's polarity is not merely *also* present but exclusive. -/

/-- A treatment axis really does generate a forward navigability obligation, so the
measurement has something to discharge. -/
theorem treatment_axis_is_obliged (p : ℝ → ℝ) :
    Obligation.axisNavigable (treatmentAxis "eigen-sign" p) ∈ (base p p p p).obligations := by
  simp [base, Registration.obligations, eigenSignArm]

/-- The control does NOT also generate the forward obligation. Without this, a
registration could carry both polarities and be discharged by whichever the data
happened to support. -/
theorem random_control_has_no_forward_obligation (p : ℝ → ℝ) :
    Obligation.axisNavigable randomAxis ∉ (base p p p p).obligations := by
  simp [base, Registration.obligations, randomControlArm, eigenSignArm,
    eigenOrderingArm, eigenMagnitudeArm, symmetrisedArm, treatmentAxis, randomAxis]

end ExotypeLiftVariant

section AxiomAudit
open ExotypeLiftVariant
#print axioms randomAxis_not_navigable
#print axioms random_control_obligation_is_reversed
#print axioms separability_is_obliged
#print axioms treatment_axis_is_obliged
#print axioms random_control_has_no_forward_obligation
end AxiomAudit
