/-
Copyright (c) 2026 Joseph Corneli. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import DarkTower.ExperimentalDesign

/-!
# Slices 1, 2, 2b: does a varying exotype grid do anything?

An EXOTYPE is the operator that rewrites genotypes. Every prior experiment fixed ONE
globally (`river-writing` = rot+2) and let genotypes vary under it. These slices give
each cell its own exotype and ask whether that buys anything at the layers below.

## Why the arms are ordered as they are

Build order is ablation order reversed: each slice's null is the slice below it, so the
ablations are the build history rather than something constructed afterwards. Slice 1's
`boring-triggered` is therefore the BASELINE for Slice 2, not `uniform-fixed` --
comparing a regulator against a dead baseline flatters it.

## What was measured (claude-11, 2026-08-03)

Slice 1: `conformist` changed the grid on 1 of 120 steps -- majority rule freezes from a
random start, so it is inert BY CONSTRUCTION. `boring-triggered` was live: active on 69
of 120 steps, driving the distribution from ~uniform to 35/40/4/1.

Slice 2: every EFE arm collapsed the grid to a SINGLE exotype, identically across 100
seeds. Conatus off gave 80/80 `:identity` (the dark room, as predicted); conatus on gave
80/80 `:chaos`. Grid activity fell 12-fold against `boring-triggered` (-57 sem).

Slice 2b tests Joe's reading that bistable endpoints mean the system needs TUNING: a
weight lambda interpolating between them should make exotype DIVERSITY peaked, and the
peak would be the candidate edge-of-chaos point at the exotype layer.
-/

namespace ExotypeGrid

open ExperimentPreregistration ExperimentalDesign

/-- What a smoke run reports. -/
structure Trace where
  /-- The policy was observed to MOVE the grid. Slice 1's `conformist` changed it once
  in 120 steps; a policy that cannot move the grid cannot be measured, and its agreement
  with a baseline reads as robustness when it is an inert treatment. -/
  policyMovesGrid : Bool
  /-- Each EFE term is reported beside the total rather than folded into it, so an
  ablation is a flag and a term's contribution is a number. -/
  termsReportedSeparately : Bool
  /-- C references only locally computable predicates. If preferences mention band,
  reach or damage the experiment assumes its conclusion. -/
  preferencesLocalOnly : Bool
  /-- Same seed regenerated byte-identically. -/
  deterministic : Bool
  deriving DecidableEq, Repr

/-- Conatus weights swept in Slice 2b, dense near zero because a preferred-hunger of
0.05 already produced full chaos, so the transition may sit very close to 0. -/
def lambdaLevels : List ℝ := [0, 0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1, 0.2, 0.4, 0.7, 1]

/-- Exotype diversity as a function of the conatus weight. Slice 2 pinned both
endpoints at a single kind, so `diversity 0 = 1` and `diversity 1 = 1` are MEASURED, not
assumed; the open question is entirely about the interior. -/
noncomputable def diversityAxis (diversity : ℝ → ℝ) : Axis where
  name := "conatus weight ↦ exotype diversity (kinds present)"
  levels := lambdaLevels
  score := diversity
  onViolation := none

/-- The bistability hypothesis as a positive control: if the collapse is genuine rather
than a tuning failure, diversity is FLAT at one kind across every weight.

Registering it this way is the point. `ArmRole.positiveControl` obliges us to prove the
predicted null, so "there is no interior" has to be established rather than assumed
whenever the sweep fails to find a peak -- and conversely a peak refutes it. -/
def constantOneKind : ℝ → ℝ := fun _ => 1

noncomputable def bistabilityAxis : Axis where
  name := "bistable: diversity pinned at one kind for every conatus weight"
  levels := lambdaLevels
  score := constantOneKind
  onViolation := none

/-- If the grid really is bistable, its axis carries no gradient and there is nothing
to tune. This is what a failed Slice 2b would have PROVED, not merely reported. -/
theorem bistability_not_navigable : ¬ bistabilityAxis.Navigable := by
  apply not_navigable_of_constant
  intro x y
  rfl

noncomputable def boringTriggeredArm : Arm where
  name := "boring-triggered (Slice 1 baseline; measured live, 69/120 steps)"
  neutral := true
  axes := []
  role := .baselineNeutral

noncomputable def efeArm (name : String) (diversity : ℝ → ℝ) : Arm where
  name := name
  neutral := false
  axes := [diversityAxis diversity]

noncomputable def bistableControlArm : Arm where
  name := "bistable collapse (positive control: no interior exists)"
  neutral := true
  axes := [bistabilityAxis]
  role := .positiveControl

/-- Flags that must be observed to act on the smoke trace. -/
def apparatusActs : Flag Trace where
  name := "policy moves the grid, terms separable, C local, run deterministic"
  observable :=
    { name := "the treatment is causally live and not circular"
      holds := fun t =>
        t.policyMovesGrid = true ∧ t.termsReportedSeparately = true ∧
        t.preferencesLocalOnly = true ∧ t.deterministic = true
      check := fun t =>
        t.policyMovesGrid && t.termsReportedSeparately &&
        t.preferencesLocalOnly && t.deterministic
      check_sound := by
        intro t h
        simpa only [Bool.and_eq_true, and_assoc] using h }

noncomputable def base (diversity : ℝ → ℝ) : Registration Trace where
  name := "exotype-grid-conatus-sweep"
  claim := .comparative
  arms := [boringTriggeredArm, efeArm "efe-lambda-sweep" diversity, bistableControlArm]
  flags := [apparatusActs]
  -- 12 weights x 100 seeds x a 120-step run at ~0.2 s, plus panels.
  estimatedCost := 40
  budgetCap := 120
  teardownDeadline := some 120

/-- A comparative claim obliges separability, so "every weight looks the same" cannot be
reported as robustness. -/
theorem separability_is_obliged (d : ℝ → ℝ) :
    Obligation.armsSeparable ∈ (base d).obligations := by
  simp [base, Registration.obligations]

/-- The bistability control carries the REVERSED obligation. -/
theorem bistability_obligation_is_reversed (d : ℝ → ℝ) :
    Obligation.axisPredictedNonNavigable bistabilityAxis ∈ (base d).obligations := by
  simp [base, Registration.obligations, bistableControlArm]

/-- Non-triviality: the swept arm generates a real forward obligation, so the run has
something to discharge rather than the registration gating nothing. -/
theorem sweep_axis_is_obliged (d : ℝ → ℝ) :
    Obligation.axisNavigable (diversityAxis d) ∈ (base d).obligations := by
  simp [base, Registration.obligations, efeArm]

end ExotypeGrid

section AxiomAudit
open ExotypeGrid
#print axioms bistability_not_navigable
#print axioms separability_is_obliged
#print axioms bistability_obligation_is_reversed
#print axioms sweep_axis_is_obliged
end AxiomAudit
