import DarkTower.WarMachine.PrecisionFromObservation
import DarkTower.WarMachine.R10ScheduledEntrypoint
import DarkTower.WarMachine.R15TemporalHierarchy
import Mathlib.Tactic

/-!
# Evidence comes from the generative process

The agent learns only from what the world sends back. Something computed from
its own beliefs contains no information it did not already have, however
carefully it is checked against itself. A step in which nothing arrives from
the world leaves its beliefs unchanged.

Parr et al. (2022), pp. 22–23, Figure 2.2
(`refs/parr2022.txt:1210-1262`) distinguishes the generative process—the true
causal structure generating observations—from the generative model, which is a
construct used to infer their causes. This distinction grounds three software
requirements: R9 cannot certify the world from its own output; R12 must keep
model-against-model consistency separate from comparison with a process
outcome; and R10 cannot count an observation-free scheduled step as liveness.

`ExactBeliefTrajectory.exactBeliefAt` includes both action-conditioned state
transition and observation update. This module needs the single-observation
Bayes lemma with no transition, so it states that finite posterior locally.

Here "independent" means generated by the process and not a function of the
agent's current belief. The mathematics does not establish that provenance for
a concrete record. A source search over `src/futon2/aif/wm/`,
`policy_prefix_admission.clj`, `policy_prefix_evidence.clj`, and
`policy_precision_carry.clj` found byte/source provenance for conditioning
steps and observations, but no field classifying the conditioned observation
as process-generated versus derived from the agent's own forecast.
-/

namespace DarkTower.WarMachine.EvidenceFromTheProcess

open scoped BigOperators
noncomputable section

variable {State Observation : Type*} [Fintype State] [Nonempty State]

abbrev Belief (State : Type*) := State → ℝ
abbrev Likelihood (State Observation : Type*) := State → Observation → ℝ

def evidence (prior : Belief State) (A : Likelihood State Observation)
    (o : Observation) : ℝ := ∑ s, prior s * A s o

/-- Finite Bayes posterior for one observation with positive evidence. -/
def posterior (prior : Belief State) (A : Likelihood State Observation)
    (o : Observation) : Belief State :=
  fun s => prior s * A s o / evidence prior A o

/-- An observation whose likelihood is state-independent carries no evidence
about which hidden state obtains. -/
theorem no_evidence_no_change (prior : Belief State) (A : Likelihood State Observation)
    (o : Observation) (normal : ∑ s, prior s = 1)
    (c : ℝ) (hc : 0 < c) (constant : ∀ s, A s o = c) :
    posterior prior A o = prior := by
  have he : evidence prior A o = c := by
    simp only [evidence, constant]
    rw [← Finset.sum_mul, normal, one_mul]
  funext s
  simp [posterior, he, constant s, hc.ne']

/-- If conditioning moves a full-support prior on a positive-evidence
observation, its likelihood must distinguish at least two hidden states. -/
theorem changed_posterior_requires_differential_likelihood
    (prior : Belief State) (A : Likelihood State Observation) (o : Observation)
    (normal : ∑ s, prior s = 1) (_full : ∀ s, 0 < prior s)
    (positive : 0 < evidence prior A o)
    (changed : posterior prior A o ≠ prior) :
    ∃ s t, A s o ≠ A t o := by
  by_contra none
  push_neg at none
  let s₀ : State := Classical.choice inferInstance
  have constant : ∀ s, A s o = A s₀ o := fun s => none s s₀
  have he : evidence prior A o = A s₀ o := by
    simp only [evidence, constant]
    rw [← Finset.sum_mul, normal, one_mul]
  exact changed (no_evidence_no_change prior A o normal _ (he ▸ positive) constant)

/-- An "observation" obtained solely by applying functions to the current
belief has a state-independent likelihood and cannot update that belief. -/
theorem self_produced_evidence_changes_nothing
    {Output SelfObservation : Type*} (prior : Belief State)
    (normal : ∑ s, prior s = 1) (make : Belief State → Output)
    (observe : Output → SelfObservation) :
    posterior prior (fun _ _ => 1) (observe (make prior)) = prior := by
  apply no_evidence_no_change prior _ _ normal 1 (by norm_num)
  intro s
  rfl

theorem posterior_rises_iff_likelihood_above_evidence
    (prior : Belief State) (A : Likelihood State Observation) (o : Observation)
    (s : State) (hp : 0 < prior s) (he : 0 < evidence prior A o) :
    prior s < posterior prior A o s ↔ evidence prior A o < A s o := by
  simp only [posterior]
  rw [lt_div_iff₀ he]
  constructor <;> intro h <;> nlinarith

abbrev ExampleState := Fin 2
inductive ExampleObservation | seen deriving DecidableEq, Fintype

def examplePrior : Belief ExampleState := fun _ => 1 / 2
def exampleLikelihood : Likelihood ExampleState ExampleObservation
  | s, .seen => if s = 0 then 3 / 4 else 1 / 4

theorem process_evidence_can_move_belief :
    posterior examplePrior exampleLikelihood .seen 0 = 3 / 4 ∧
      posterior examplePrior exampleLikelihood .seen ≠ examplePrior := by
  have he : evidence examplePrior exampleLikelihood .seen = 1 / 2 := by
    unfold evidence
    rw [Fin.sum_univ_two]
    change (1 / 2 * (3 / 4) + 1 / 2 * (1 / 4) : ℝ) = 1 / 2
    norm_num
  constructor
  · norm_num [posterior, he, examplePrior, exampleLikelihood]
  · intro equal
    have := congrFun equal (0 : ExampleState)
    norm_num [posterior, he, examplePrior, exampleLikelihood] at this

/-! ## One observation-free step changes nothing -/

structure EpistemicState (State Class : Type*) where
  belief : Belief State
  precision : ℝ
  counts : Class → R15TemporalHierarchy.BetaCounts

/-- The three explicit no-update claims: a state-independent observation
leaves the state belief fixed; constant F leaves policy precision fixed; and
an unwitnessed outcome cannot be admitted as slow learning. -/
theorem nothing_inferred_or_learned
    {Policy : Type*} [Fintype Policy] [Nonempty Policy]
    (prior : Belief State) (A : Likelihood State Observation) (o : Observation)
    (normal : ∑ s, prior s = 1) (c : ℝ) (hc : 0 < c)
    (constantA : ∀ s, A s o = c)
    (beta : ℝ) (G : Policy → ℝ) (f : ℝ)
    (slow : R15TemporalHierarchy.TwoTickRecord)
    (unwitnessed : slow.outcome.witnessed = false) :
    posterior prior A o = prior ∧
      PrecisionFromObservation.updatedPrecision beta G (fun _ => f) = 1 / beta ∧
      ¬ R15TemporalHierarchy.TwoTickFeedback slow := by
  exact ⟨no_evidence_no_change prior A o normal c hc constantA,
    (PrecisionFromObservation.constant_F_no_update beta G f).2.2,
    R15TemporalHierarchy.unwitnessed_never_accepted slow unwitnessed⟩

/-- If the observable state is the triple of belief, precision, and learned
counts, the no-update result makes the tick a no-op, hence not `LiveTick`. -/
theorem no_update_is_not_live {Observable : Type} [DecidableEq Observable]
    (state : Observable) :
    ¬ R10ScheduledEntrypoint.LiveTick
      ({ beforeState := state, afterState := state, reportedLive := false } :
        R10ScheduledEntrypoint.TickOutcome Observable) := by
  simp [R10ScheduledEntrypoint.LiveTick, R10ScheduledEntrypoint.ChangedState]

/-! ## Small retained-record boundaries -/

inductive ObservationSource | process | agentOutput deriving DecidableEq

structure EvidenceRecord where
  source : ObservationSource

def NoSelfCertification (r : EvidenceRecord) : Prop :=
  r.source = .process

def selfForecastEvidence : EvidenceRecord := ⟨.agentOutput⟩

theorem self_forecast_refused : ¬ NoSelfCertification selfForecastEvidence := by
  simp [NoSelfCertification, selfForecastEvidence]

inductive ComparisonTarget | modelScore | processOutcome deriving DecidableEq

structure CalibrationRecord where
  layer1Target : ComparisonTarget
  layer2Target : ComparisonTarget
  countedAsWorldEvidence : Bool

def CalibrationConforms (r : CalibrationRecord) : Prop :=
  r.countedAsWorldEvidence = true → r.layer2Target = .processOutcome

def modelAgainstModelCounted : CalibrationRecord :=
  ⟨.modelScore, .modelScore, true⟩

theorem model_against_model_is_not_world_evidence :
    ¬ CalibrationConforms modelAgainstModelCounted := by
  simp [CalibrationConforms, modelAgainstModelCounted]

end
end DarkTower.WarMachine.EvidenceFromTheProcess
