import DarkTower.WarMachine.PrecisionFromObservation
import DarkTower.WarMachine.R10ScheduledEntrypoint
import DarkTower.WarMachine.R15TemporalHierarchy
import Mathlib.Tactic

/-!
# Evidence comes from the generative process

The agent learns only from what the world sends back. Something computed from
its own beliefs contains no information it did not already have, however
carefully it is checked against itself. A step in which nothing arrives from
the world leaves its beliefs unchanged.

Parr et al. (2022), pp. 22–23, Figure 2.2
(`refs/parr2022.txt:1210-1262`) distinguishes the generative process—the true
causal structure generating observations—from the generative model, which is a
construct used to infer their causes. This distinction grounds three software
requirements: R9 cannot certify the world from its own output; R12 must keep
model-against-model consistency separate from comparison with a process
outcome; and R10 cannot count an observation-free scheduled step as liveness.

`ExactBeliefTrajectory.exactBeliefAt` includes both action-conditioned state
transition and observation update. This module needs the single-observation
Bayes lemma with no transition, so it states that finite posterior locally.

Here "independent" means generated by the process and not a function of the
agent's current belief. The mathematics does not establish that provenance for
a concrete record. A source search over `src/futon2/aif/wm/`,
`policy_prefix_admission.clj`, `policy_prefix_evidence.clj`, and
`policy_precision_carry.clj` found byte/source provenance for conditioning
steps and observations, but no field classifying the conditioned observation
as process-generated versus derived from the agent's own forecast.
-/

namespace DarkTower.WarMachine.EvidenceFromTheProcess

open scoped BigOperators
noncomputable section

variable {State Observation : Type*} [Fintype State] [Nonempty State]

abbrev Belief (State : Type*) := State → ℝ
abbrev Likelihood (State Observation : Type*) := State → Observation → ℝ

def evidence (prior : Belief State) (A : Likelihood State Observation)
    (o : Observation) : ℝ := ∑ s, prior s * A s o

/-- Finite Bayes posterior for one observation with positive evidence. -/
def posterior (prior : Belief State) (A : Likelihood State Observation)
    (o : Observation) : Belief State :=
  fun s => prior s * A s o / evidence prior A o

/-- An observation whose likelihood is state-independent carries no evidence
about which hidden state obtains. -/
theorem no_evidence_no_change (prior : Belief State) (A : Likelihood State Observation)
    (o : Observation) (normal : ∑ s, prior s = 1)
    (c : ℝ) (hc : 0 < c) (constant : ∀ s, A s o = c) :
    posterior prior A o = prior := by
  have he : evidence prior A o = c := by
    simp only [evidence, constant]
    rw [← Finset.sum_mul, normal, one_mul]
  funext s
  simp [posterior, he, constant s, hc.ne']

/-- If conditioning moves a full-support prior on a positive-evidence
observation, its likelihood must distinguish at least two hidden states. -/
theorem changed_posterior_requires_differential_likelihood
    (prior : Belief State) (A : Likelihood State Observation) (o : Observation)
    (normal : ∑ s, prior s = 1) (_full : ∀ s, 0 < prior s)
    (positive : 0 < evidence prior A o)
    (changed : posterior prior A o ≠ prior) :
    ∃ s t, A s o ≠ A t o := by
  by_contra none
  push_neg at none
  let s₀ : State := Classical.choice inferInstance
  have constant : ∀ s, A s o = A s₀ o := fun s => none s s₀
  have he : evidence prior A o = A s₀ o := by
    simp only [evidence, constant]
    rw [← Finset.sum_mul, normal, one_mul]
  exact changed (no_evidence_no_change prior A o normal _ (he ▸ positive) constant)

/-- The likelihood of something the agent produced from its own belief. The
agent's output may be random, with distribution `produce belief` over what it
reports; that distribution depends on the belief and not on the hidden state,
so the likelihood is the same function of the report for every state. -/
def selfLikelihood {SelfObservation : Type*}
    (produce : Belief State → SelfObservation → ℝ) (belief : Belief State) :
    Likelihood State SelfObservation :=
  fun _ report => produce belief report

/-- Conditioning on something the agent produced from its own belief changes
nothing, whatever the rule that produced it and whichever report came out.
This is why a verdict resting on the maker's own output, or a forecast checked
against the model's own later score, cannot move a belief about the world. -/
theorem self_produced_evidence_changes_nothing
    {SelfObservation : Type*} (prior : Belief State) (normal : ∑ s, prior s = 1)
    (produce : Belief State → SelfObservation → ℝ) (report : SelfObservation)
    (possible : 0 < produce prior report) :
    posterior prior (selfLikelihood produce prior) report = prior :=
  no_evidence_no_change prior _ report normal (produce prior report) possible
    (fun _ => rfl)

/-- The deterministic case: the report is a function of the belief alone. -/
theorem self_computed_report_changes_nothing
    {SelfObservation : Type*} [DecidableEq SelfObservation]
    (prior : Belief State) (normal : ∑ s, prior s = 1)
    (compute : Belief State → SelfObservation) :
    posterior prior
      (selfLikelihood (fun belief report => if report = compute belief then 1 else 0) prior)
      (compute prior) = prior :=
  self_produced_evidence_changes_nothing prior normal _ (compute prior) (by simp)

theorem posterior_rises_iff_likelihood_above_evidence
    (prior : Belief State) (A : Likelihood State Observation) (o : Observation)
    (s : State) (hp : 0 < prior s) (he : 0 < evidence prior A o) :
    prior s < posterior prior A o s ↔ evidence prior A o < A s o := by
  simp only [posterior]
  rw [lt_div_iff₀ he]
  constructor <;> intro h <;> nlinarith

abbrev ExampleState := Fin 2
inductive ExampleObservation | seen deriving DecidableEq, Fintype

def examplePrior : Belief ExampleState := fun _ => 1 / 2
def exampleLikelihood : Likelihood ExampleState ExampleObservation
  | s, .seen => if s = 0 then 3 / 4 else 1 / 4

theorem process_evidence_can_move_belief :
    posterior examplePrior exampleLikelihood .seen 0 = 3 / 4 ∧
      posterior examplePrior exampleLikelihood .seen ≠ examplePrior := by
  have he : evidence examplePrior exampleLikelihood .seen = 1 / 2 := by
    unfold evidence
    rw [Fin.sum_univ_two]
    change (1 / 2 * (3 / 4) + 1 / 2 * (1 / 4) : ℝ) = 1 / 2
    norm_num
  constructor
  · norm_num [posterior, he, examplePrior, exampleLikelihood]
  · intro equal
    have := congrFun equal (0 : ExampleState)
    norm_num [posterior, he, examplePrior, exampleLikelihood] at this

/-! ## One observation-free step changes nothing -/

/-- What a tick can change: the belief over hidden states, the policy
temperature, and the counts of what worked. -/
structure EpistemicState (State Class : Type*) where
  belief : Belief State
  temperature : ℝ
  counts : Class → R15TemporalHierarchy.BetaCounts

/-- The state after one tick that conditions the belief on `o`, applies the
precision update with per-policy free energy `F`, and admits no outcome into
the counts. -/
def afterTick {Class Policy : Type*} [Fintype Policy] [Nonempty Policy]
    (before : EpistemicState State Class) (A : Likelihood State Observation)
    (o : Observation) (beta : ℝ) (G F : Policy → ℝ) : EpistemicState State Class :=
  { belief := posterior before.belief A o
    temperature := beta
    counts := before.counts }

/-- Nothing inferred, nothing learned: if the observation's likelihood is the
same in every state and the per-policy free energy is the same for every
policy, the tick leaves the whole state exactly where it was. -/
theorem uninformative_tick_changes_nothing
    {Class Policy : Type*} [Fintype Policy] [Nonempty Policy]
    (before : EpistemicState State Class) (A : Likelihood State Observation)
    (o : Observation) (normal : ∑ s, before.belief s = 1)
    (c : ℝ) (hc : 0 < c) (constantA : ∀ s, A s o = c)
    (E G : Policy → ℝ) (f beta : ℝ) (hprior : 0 < before.temperature)
    (fixed : PrecisionFromObservation.IsPosteriorTemperature
      before.temperature beta E G (fun _ => f)) :
    afterTick before A o beta G (fun _ => f) = before := by
  have belief := no_evidence_no_change before.belief A o normal c hc constantA
  have temperature := (PrecisionFromObservation.constant_F_posterior_temperature_iff
    hprior E G f).mp fixed
  cases before
  simp_all [afterTick]

/-- An outcome that was not witnessed is never admitted into the counts. -/
theorem unwitnessed_outcome_teaches_nothing
    (slow : R15TemporalHierarchy.TwoTickRecord)
    (unwitnessed : slow.outcome.witnessed = false) :
    ¬ R15TemporalHierarchy.TwoTickFeedback slow :=
  R15TemporalHierarchy.unwitnessed_never_accepted slow unwitnessed

open Classical in
/-- Such a tick is not live in the sense of `R10ScheduledEntrypoint`, whatever
label it was given: its state after is its state before. -/
theorem uninformative_tick_is_not_live
    {Class Policy : Type} {State : Type} [Fintype State] [Nonempty State]
    {Observation : Type} [Fintype Policy] [Nonempty Policy]
    (before : EpistemicState State Class) (A : Likelihood State Observation)
    (o : Observation) (normal : ∑ s, before.belief s = 1)
    (c : ℝ) (hc : 0 < c) (constantA : ∀ s, A s o = c)
    (E G : Policy → ℝ) (f beta : ℝ) (hprior : 0 < before.temperature)
    (fixed : PrecisionFromObservation.IsPosteriorTemperature
      before.temperature beta E G (fun _ => f)) (label : Bool) :
    ¬ R10ScheduledEntrypoint.LiveTick
      ({ beforeState := before
         afterState := afterTick before A o beta G (fun _ => f)
         reportedLive := label } :
        R10ScheduledEntrypoint.TickOutcome (EpistemicState State Class)) := by
  simp only [R10ScheduledEntrypoint.LiveTick, R10ScheduledEntrypoint.ChangedState,
    uninformative_tick_changes_nothing before A o normal c hc constantA E G f beta hprior fixed]
  simp

/-! ## Small retained-record boundaries -/

inductive ObservationSource | process | agentOutput deriving DecidableEq

structure EvidenceRecord where
  source : ObservationSource

def NoSelfCertification (r : EvidenceRecord) : Prop :=
  r.source = .process

def selfForecastEvidence : EvidenceRecord := ⟨.agentOutput⟩

theorem self_forecast_refused : ¬ NoSelfCertification selfForecastEvidence := by
  simp [NoSelfCertification, selfForecastEvidence]

inductive ComparisonTarget | modelScore | processOutcome deriving DecidableEq

structure CalibrationRecord where
  layer1Target : ComparisonTarget
  layer2Target : ComparisonTarget
  countedAsWorldEvidence : Bool

def CalibrationConforms (r : CalibrationRecord) : Prop :=
  r.countedAsWorldEvidence = true → r.layer2Target = .processOutcome

def modelAgainstModelCounted : CalibrationRecord :=
  ⟨.modelScore, .modelScore, true⟩

theorem model_against_model_is_not_world_evidence :
    ¬ CalibrationConforms modelAgainstModelCounted := by
  simp [CalibrationConforms, modelAgainstModelCounted]

end
end DarkTower.WarMachine.EvidenceFromTheProcess
