import DarkTower.WarMachine.Holes

/-!
# RUN4 preregistration: what accepting a run-conformance certificate asserts

GENERATED by `futon2:holes/labs/wm-contract/run4_prereg_transcribe.bb` from the
committed certificates under `futon2:holes/labs/wm-contract/runs/`. Edit a
certificate and regenerate; do not edit the literals below.

Joe, 2026-09-05: "i don't get a sense of how far off we are from being able to
do RUN4 without it being a waste of time. Maybe RUN4 needs its own
manifest/preregistration. That is unlikely to fit in Voxterm but it could go
well in Lean." This module is that manifest. It is a PREREGISTRATION: it fixes,
before the acceptance, what the acceptance would be an acceptance OF, so that a
later reader can tell an assertion that was declared in advance from one that
was assembled to fit the outcome.

WHAT IT DOES NOT DO. It accepts nothing and closes nothing.
`Holes.wmRunConformsToWiring` stays `mkHole` until Joe accepts a certificate
over a run he judges qualifying; the RUN4 ruling (futon2 `worklist.edn`
`:run4-lean-ruling`, 2026-09-03) reserves both the acceptance and the judgement
of which run qualifies, and nothing here anticipates either.

THE SPLIT BETWEEN THIS MODULE AND THE METER. Lean decides the in-repo part: the
named theorems ELABORATE at the types stated below, the manifest's own census is
decided, and the invalidator partition is decided. What Lean cannot see is
whether a pinned file still hashes to its pinned value, or whether a declared
piece of pending work has landed since the pin. That is
`futon2:holes/labs/wm-contract/run4_readiness.bb`, which compares these pins to
the live repositories and reports READY or BLOCKED-ON.

WHY THE ASSERTION SET IS CITED BY REFERENCE. `run4Assertions` carries theorem
NAMES as strings, for the reader. What binds them is the block of definitions
below it: each is the named theorem itself, at a restated type. A rename, a
removal, or a census number moving breaks this module at `lake build` -- which
is the detection a string list cannot give.
-/

namespace DarkTower.WarMachine.Run4Preregistration

open Holes

/-- A run for which a run-conformance certificate has been minted and not yet
accepted. -/
inductive CandidateRun where
  | s5
  | re5
  deriving DecidableEq, Repr

/-- Where a certificate stands. `accepted` exists so that the manifest can say
which value it is NOT in, rather than leaving the reader to infer it from an
absence. -/
inductive AcceptanceStatus where
  | mintedAwaitingAcceptance
  | accepted
  deriving DecidableEq, Repr

/-- One theorem that an acceptance would be an acceptance OF. -/
structure PreregAssertion where
  /-- The fully qualified name, carried for the reader; the citation that binds
  it is the definition block below. -/
  theoremName : String
  /-- The run the theorem is about. -/
  run : CandidateRun
  /-- Minted and awaiting acceptance, for every row of this manifest. -/
  status : AcceptanceStatus
  deriving DecidableEq, Repr

/-- How a pinned authority is named. -/
inductive PinKind where
  | sha256
  | gitCommit
  deriving DecidableEq, Repr

/-- One authority the assertion set is pinned to. COPIED from the certificates,
which the U49 producer generated from the two pinned sources; not re-taken here,
because a manifest that re-pinned would agree with today's tree instead of with
the certificates. -/
structure PinnedAuthority where
  /-- `control-map`, `trace:<run>`, `contract:<row>`. -/
  key : String
  /-- Whether `identity` is a content hash or a commit. -/
  kind : PinKind
  /-- The pinned value, verbatim. -/
  identity : String
  deriving DecidableEq, Repr

/-- The declared candidate invalidators: pending work that could make an
acceptance stale on arrival. Declared in advance and closed: an invalidator
discovered later is a new row and a new commit, not a quiet addition. -/
inductive InvalidatorId where
  | r16BaseDrawingStroke
  | postPinControlMapDecisions
  | f1ModelExtensions
  | selectionDiscriminationVerdicts
  deriving DecidableEq, Repr

/-- One declared invalidator with the one question this manifest can settle
answered. `touchesCertificateDefinitions` is a property of what the
transcription READS and of what the emitted block CONTAINS, so it is measurable
here; whether the work has LANDED is a property of the live repositories and is
the meter's line. The grounds for each answer are in
`futon2:holes/labs/wm-contract/runs/F2-run4-preregistration/03-invalidators.edn`,
with the counts each was decided from. -/
structure Invalidator where
  /-- Which declared item. -/
  id : InvalidatorId
  /-- Would it change a definition the certificates are stated over? -/
  touchesCertificateDefinitions : Bool
  /-- Does it carry an executable measurement? An unmeasured item blocks. -/
  measured : Bool
  deriving DecidableEq, Repr

/-- THE ASSERTION SET. -/
def run4Assertions : List PreregAssertion :=
  [{ theoremName := "DarkTower.WarMachine.Holes.wmS5RunConformsToDrawnWiring", run := .s5, status := .mintedAwaitingAcceptance },
   { theoremName := "DarkTower.WarMachine.Holes.wmS5RouteCensus", run := .s5, status := .mintedAwaitingAcceptance },
   { theoremName := "DarkTower.WarMachine.Holes.wmRe5RunConformsToDrawnWiring", run := .re5, status := .mintedAwaitingAcceptance },
   { theoremName := "DarkTower.WarMachine.Holes.wmRe5RouteCensus", run := .re5, status := .mintedAwaitingAcceptance }]

/-- THE PINNED AUTHORITIES. -/
def run4Authorities : List PinnedAuthority :=
  [{ key := "control-map", kind := .sha256, identity := "161d0abffd21551078ac2d7a87427e6cacafbfca0695c09a496260be21fafdec" },
   { key := "trace:2026-09-01-s5", kind := .sha256, identity := "c3480955286e548be6fd4bbde80e5081446cfaaac1500294e2de1fa44e2d7c67" },
   { key := "trace:2026-09-04-re5", kind := .sha256, identity := "f343432d772986ddc2f7fe38107913afc997201ebae9b6240dff152e235b1120" },
   { key := "contract:U49", kind := .gitCommit, identity := "11c2e44affa167bf85b0a2d7c29d8705f89a8d08" },
   { key := "contract:RE5", kind := .gitCommit, identity := "581034b67e47240b7a4003dc39bdd7dd545e1daf" }]

/-- THE DECLARED INVALIDATION SET. -/
def run4Invalidators : List Invalidator :=
  [{ id := .r16BaseDrawingStroke, touchesCertificateDefinitions := false, measured := true },
   { id := .postPinControlMapDecisions, touchesCertificateDefinitions := true, measured := true },
   { id := .f1ModelExtensions, touchesCertificateDefinitions := false, measured := true },
   { id := .selectionDiscriminationVerdicts, touchesCertificateDefinitions := false, measured := true }]

/-- CITED BY REFERENCE: the conformance theorem for `2026-09-01-s5`, at its
stated type. If `wmS5RunConformsToDrawnWiring` were renamed, removed or
restated, this definition would not elaborate. -/
theorem run4CertifiedS5Conformance : runConformsToDrawnWiring s5Routes :=
  wmS5RunConformsToDrawnWiring

/-- CITED BY REFERENCE WITH ITS NUMBERS RESTATED: the census for `2026-09-01-s5`.
The eleven numbers are written out rather than cited by name, so that a census
number moving breaks this module -- an acceptance made after such a move would
be an acceptance of different numbers than the ones preregistered here. -/
theorem run4CertifiedS5Census :
    s5Routes.length = 4 ∧
      s5Hops.length = 36 ∧
      s5Hops.dedup.length = 9 ∧
      (s5Hops.dedup.filter (fun h => decide (classifyHop h = HopClass.drawn))).length = 2 ∧
      (s5Hops.dedup.filter (fun h => decide (classifyHop h = HopClass.routeMeasured))).length = 5 ∧
      (s5Hops.dedup.filter (fun h => decide (classifyHop h = HopClass.excludedDependencyGrain))).length = 1 ∧
      (s5Hops.dedup.filter (fun h => decide (classifyHop h = HopClass.rulingUnrealised))).length = 1 ∧
      (s5Hops.dedup.filter (fun h => decide (classifyHop h = HopClass.refutation))).length = 0 ∧
      (s5Hops.dedup.filter (fun h => decide (classifyHop h = HopClass.unmapped))).length = 0 ∧
      figureDrawnEdges.length = 22 ∧
      s5UnfiredDrawnEdges.length = 19 :=
  wmS5RouteCensus

/-- CITED BY REFERENCE: the conformance theorem for `2026-09-04-re5`, at its
stated type. If `wmRe5RunConformsToDrawnWiring` were renamed, removed or
restated, this definition would not elaborate. -/
theorem run4CertifiedRe5Conformance : runConformsToDrawnWiring re5Routes :=
  wmRe5RunConformsToDrawnWiring

/-- CITED BY REFERENCE WITH ITS NUMBERS RESTATED: the census for `2026-09-04-re5`.
The eleven numbers are written out rather than cited by name, so that a census
number moving breaks this module -- an acceptance made after such a move would
be an acceptance of different numbers than the ones preregistered here. -/
theorem run4CertifiedRe5Census :
    re5Routes.length = 4 ∧
      re5Hops.length = 36 ∧
      re5Hops.dedup.length = 9 ∧
      (re5Hops.dedup.filter (fun h => decide (classifyHop h = HopClass.drawn))).length = 2 ∧
      (re5Hops.dedup.filter (fun h => decide (classifyHop h = HopClass.routeMeasured))).length = 5 ∧
      (re5Hops.dedup.filter (fun h => decide (classifyHop h = HopClass.excludedDependencyGrain))).length = 1 ∧
      (re5Hops.dedup.filter (fun h => decide (classifyHop h = HopClass.rulingUnrealised))).length = 1 ∧
      (re5Hops.dedup.filter (fun h => decide (classifyHop h = HopClass.refutation))).length = 0 ∧
      (re5Hops.dedup.filter (fun h => decide (classifyHop h = HopClass.unmapped))).length = 0 ∧
      figureDrawnEdges.length = 22 ∧
      re5UnfiredDrawnEdges.length = 19 :=
  wmRe5RouteCensus

/-- THE MANIFEST'S OWN CENSUS, decided: how many assertions, all of them awaiting
acceptance; how many pinned authorities; how many declared invalidators, how many
of them touch the certificates' definitions, and how many are unmeasured (an
unmeasured invalidator is a declared hazard nobody checked, so the count that
matters is that it is zero). -/
theorem wmRun4PreregCensus :
    run4Assertions.length = 4 ∧
      (run4Assertions.filter
        (fun a => decide (a.status = AcceptanceStatus.mintedAwaitingAcceptance))).length = 4 ∧
      run4Authorities.length = 5 ∧
      run4Invalidators.length = 4 ∧
      (run4Invalidators.filter (fun i => i.touchesCertificateDefinitions)).length = 1 ∧
      (run4Invalidators.filter (fun i => !i.measured)).length = 0 := by
  decide

/-- WHICH DECLARED INVALIDATORS TOUCH THE CERTIFICATES' DEFINITIONS, decided and
named rather than counted. This is the manifest entry the ruling asked for:
`likely disjoint` is not a manifest entry, so each declared item carries a
measured answer and the answers are stated as a list, which is false if an item
is added, removed or reclassified without regenerating. -/
theorem wmRun4InvalidatorsTouchingDefinitions :
    (run4Invalidators.filter (fun i => i.touchesCertificateDefinitions)).map (fun i => i.id)
      = [InvalidatorId.postPinControlMapDecisions] := by
  decide

end DarkTower.WarMachine.Run4Preregistration
